// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _ENetProtocolSendUnsequenced {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_CHAR$LAYOUT.withName("command"),
            Constants$root.C_CHAR$LAYOUT.withName("channelID"),
            Constants$root.C_SHORT$LAYOUT.withName("reliableSequenceNumber")
        ).withName("header"),
        Constants$root.C_SHORT$LAYOUT.withName("unsequencedGroup"),
        Constants$root.C_SHORT$LAYOUT.withName("dataLength")
    ).withName("_ENetProtocolSendUnsequenced");
    public static MemoryLayout $LAYOUT() {
        return _ENetProtocolSendUnsequenced.$struct$LAYOUT;
    }
    public static MemorySegment header$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    static final VarHandle unsequencedGroup$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("unsequencedGroup"));
    public static VarHandle unsequencedGroup$VH() {
        return _ENetProtocolSendUnsequenced.unsequencedGroup$VH;
    }
    public static short unsequencedGroup$get(MemorySegment seg) {
        return (short)_ENetProtocolSendUnsequenced.unsequencedGroup$VH.get(seg);
    }
    public static void unsequencedGroup$set( MemorySegment seg, short x) {
        _ENetProtocolSendUnsequenced.unsequencedGroup$VH.set(seg, x);
    }
    public static short unsequencedGroup$get(MemorySegment seg, long index) {
        return (short)_ENetProtocolSendUnsequenced.unsequencedGroup$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void unsequencedGroup$set(MemorySegment seg, long index, short x) {
        _ENetProtocolSendUnsequenced.unsequencedGroup$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle dataLength$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dataLength"));
    public static VarHandle dataLength$VH() {
        return _ENetProtocolSendUnsequenced.dataLength$VH;
    }
    public static short dataLength$get(MemorySegment seg) {
        return (short)_ENetProtocolSendUnsequenced.dataLength$VH.get(seg);
    }
    public static void dataLength$set( MemorySegment seg, short x) {
        _ENetProtocolSendUnsequenced.dataLength$VH.set(seg, x);
    }
    public static short dataLength$get(MemorySegment seg, long index) {
        return (short)_ENetProtocolSendUnsequenced.dataLength$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void dataLength$set(MemorySegment seg, long index, short x) {
        _ENetProtocolSendUnsequenced.dataLength$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


