// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _QualityOfService {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("TokenRate"),
            Constants$root.C_LONG$LAYOUT.withName("TokenBucketSize"),
            Constants$root.C_LONG$LAYOUT.withName("PeakBandwidth"),
            Constants$root.C_LONG$LAYOUT.withName("Latency"),
            Constants$root.C_LONG$LAYOUT.withName("DelayVariation"),
            Constants$root.C_LONG$LAYOUT.withName("ServiceType"),
            Constants$root.C_LONG$LAYOUT.withName("MaxSduSize"),
            Constants$root.C_LONG$LAYOUT.withName("MinimumPolicedSize")
        ).withName("SendingFlowspec"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("TokenRate"),
            Constants$root.C_LONG$LAYOUT.withName("TokenBucketSize"),
            Constants$root.C_LONG$LAYOUT.withName("PeakBandwidth"),
            Constants$root.C_LONG$LAYOUT.withName("Latency"),
            Constants$root.C_LONG$LAYOUT.withName("DelayVariation"),
            Constants$root.C_LONG$LAYOUT.withName("ServiceType"),
            Constants$root.C_LONG$LAYOUT.withName("MaxSduSize"),
            Constants$root.C_LONG$LAYOUT.withName("MinimumPolicedSize")
        ).withName("ReceivingFlowspec"),
        MemoryLayout.structLayout(
            Constants$root.C_LONG$LAYOUT.withName("len"),
            MemoryLayout.paddingLayout(32),
            Constants$root.C_POINTER$LAYOUT.withName("buf")
        ).withName("ProviderSpecific")
    ).withName("_QualityOfService");
    public static MemoryLayout $LAYOUT() {
        return _QualityOfService.$struct$LAYOUT;
    }
    public static MemorySegment SendingFlowspec$slice(MemorySegment seg) {
        return seg.asSlice(0, 32);
    }
    public static MemorySegment ReceivingFlowspec$slice(MemorySegment seg) {
        return seg.asSlice(32, 32);
    }
    public static MemorySegment ProviderSpecific$slice(MemorySegment seg) {
        return seg.asSlice(64, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


