// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class _SOCKET_ADDRESS {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("lpSockaddr"),
        Constants$root.C_LONG$LAYOUT.withName("iSockaddrLength"),
        MemoryLayout.paddingLayout(32)
    ).withName("_SOCKET_ADDRESS");
    public static MemoryLayout $LAYOUT() {
        return _SOCKET_ADDRESS.$struct$LAYOUT;
    }
    static final VarHandle lpSockaddr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("lpSockaddr"));
    public static VarHandle lpSockaddr$VH() {
        return _SOCKET_ADDRESS.lpSockaddr$VH;
    }
    public static MemoryAddress lpSockaddr$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)_SOCKET_ADDRESS.lpSockaddr$VH.get(seg);
    }
    public static void lpSockaddr$set( MemorySegment seg, MemoryAddress x) {
        _SOCKET_ADDRESS.lpSockaddr$VH.set(seg, x);
    }
    public static MemoryAddress lpSockaddr$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)_SOCKET_ADDRESS.lpSockaddr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void lpSockaddr$set(MemorySegment seg, long index, MemoryAddress x) {
        _SOCKET_ADDRESS.lpSockaddr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle iSockaddrLength$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("iSockaddrLength"));
    public static VarHandle iSockaddrLength$VH() {
        return _SOCKET_ADDRESS.iSockaddrLength$VH;
    }
    public static int iSockaddrLength$get(MemorySegment seg) {
        return (int)_SOCKET_ADDRESS.iSockaddrLength$VH.get(seg);
    }
    public static void iSockaddrLength$set( MemorySegment seg, int x) {
        _SOCKET_ADDRESS.iSockaddrLength$VH.set(seg, x);
    }
    public static int iSockaddrLength$get(MemorySegment seg, long index) {
        return (int)_SOCKET_ADDRESS.iSockaddrLength$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void iSockaddrLength$set(MemorySegment seg, long index, int x) {
        _SOCKET_ADDRESS.iSockaddrLength$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


