// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1246 {

    static final FunctionDescriptor OleRegGetMiscStatus$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleRegGetMiscStatus$MH = RuntimeHelper.downcallHandle(
        "OleRegGetMiscStatus",
        constants$1246.OleRegGetMiscStatus$FUNC
    );
    static final FunctionDescriptor OleRegEnumFormatEtc$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleRegEnumFormatEtc$MH = RuntimeHelper.downcallHandle(
        "OleRegEnumFormatEtc",
        constants$1246.OleRegEnumFormatEtc$FUNC
    );
    static final FunctionDescriptor OleRegEnumVerbs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleRegEnumVerbs$MH = RuntimeHelper.downcallHandle(
        "OleRegEnumVerbs",
        constants$1246.OleRegEnumVerbs$FUNC
    );
    static final FunctionDescriptor OleConvertOLESTREAMToIStorage$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleConvertOLESTREAMToIStorage$MH = RuntimeHelper.downcallHandle(
        "OleConvertOLESTREAMToIStorage",
        constants$1246.OleConvertOLESTREAMToIStorage$FUNC
    );
    static final FunctionDescriptor OleConvertIStorageToOLESTREAM$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleConvertIStorageToOLESTREAM$MH = RuntimeHelper.downcallHandle(
        "OleConvertIStorageToOLESTREAM",
        constants$1246.OleConvertIStorageToOLESTREAM$FUNC
    );
    static final FunctionDescriptor OleDoAutoConvert$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OleDoAutoConvert$MH = RuntimeHelper.downcallHandle(
        "OleDoAutoConvert",
        constants$1246.OleDoAutoConvert$FUNC
    );
}


