// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1112 {

    static final FunctionDescriptor IOleInPlaceActiveObject_TranslateAccelerator_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IOleInPlaceActiveObject_TranslateAccelerator_Proxy$MH = RuntimeHelper.downcallHandle(
        "IOleInPlaceActiveObject_TranslateAccelerator_Proxy",
        constants$1112.IOleInPlaceActiveObject_TranslateAccelerator_Proxy$FUNC
    );
    static final FunctionDescriptor IOleInPlaceActiveObject_TranslateAccelerator_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IOleInPlaceActiveObject_TranslateAccelerator_Stub$MH = RuntimeHelper.downcallHandle(
        "IOleInPlaceActiveObject_TranslateAccelerator_Stub",
        constants$1112.IOleInPlaceActiveObject_TranslateAccelerator_Stub$FUNC
    );
    static final FunctionDescriptor IOleInPlaceActiveObject_ResizeBorder_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle IOleInPlaceActiveObject_ResizeBorder_Proxy$MH = RuntimeHelper.downcallHandle(
        "IOleInPlaceActiveObject_ResizeBorder_Proxy",
        constants$1112.IOleInPlaceActiveObject_ResizeBorder_Proxy$FUNC
    );
    static final FunctionDescriptor IOleInPlaceActiveObject_ResizeBorder_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle IOleInPlaceActiveObject_ResizeBorder_Stub$MH = RuntimeHelper.downcallHandle(
        "IOleInPlaceActiveObject_ResizeBorder_Stub",
        constants$1112.IOleInPlaceActiveObject_ResizeBorder_Stub$FUNC
    );
    static final FunctionDescriptor IViewObject_Draw_Proxy$pfnContinue$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle IViewObject_Draw_Proxy$pfnContinue$MH = RuntimeHelper.downcallHandle(
        constants$1112.IViewObject_Draw_Proxy$pfnContinue$FUNC
    );
}


