// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$931 {

    static final FunctionDescriptor WritePrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WritePrinter$MH = RuntimeHelper.downcallHandle(
        "WritePrinter",
        constants$931.WritePrinter$FUNC
    );
    static final FunctionDescriptor FlushPrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle FlushPrinter$MH = RuntimeHelper.downcallHandle(
        "FlushPrinter",
        constants$931.FlushPrinter$FUNC
    );
    static final FunctionDescriptor EndPagePrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EndPagePrinter$MH = RuntimeHelper.downcallHandle(
        "EndPagePrinter",
        constants$931.EndPagePrinter$FUNC
    );
    static final FunctionDescriptor AbortPrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AbortPrinter$MH = RuntimeHelper.downcallHandle(
        "AbortPrinter",
        constants$931.AbortPrinter$FUNC
    );
    static final FunctionDescriptor ReadPrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReadPrinter$MH = RuntimeHelper.downcallHandle(
        "ReadPrinter",
        constants$931.ReadPrinter$FUNC
    );
    static final FunctionDescriptor EndDocPrinter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EndDocPrinter$MH = RuntimeHelper.downcallHandle(
        "EndDocPrinter",
        constants$931.EndDocPrinter$FUNC
    );
}


