// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$887 {

    static final FunctionDescriptor RpcSsSwapClientAllocFree$ClientFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcSsSwapClientAllocFree$ClientFree$MH = RuntimeHelper.downcallHandle(
        constants$887.RpcSsSwapClientAllocFree$ClientFree$FUNC
    );
    static final FunctionDescriptor RpcSsSwapClientAllocFree$OldClientAlloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle RpcSsSwapClientAllocFree$OldClientAlloc$MH = RuntimeHelper.downcallHandle(
        constants$887.RpcSsSwapClientAllocFree$OldClientAlloc$FUNC
    );
    static final FunctionDescriptor RpcSsSwapClientAllocFree$OldClientFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcSsSwapClientAllocFree$OldClientFree$MH = RuntimeHelper.downcallHandle(
        constants$887.RpcSsSwapClientAllocFree$OldClientFree$FUNC
    );
}


