// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$185 {

    static final FunctionDescriptor GetVolumeNameForVolumeMountPointW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetVolumeNameForVolumeMountPointW$MH = RuntimeHelper.downcallHandle(
        "GetVolumeNameForVolumeMountPointW",
        constants$185.GetVolumeNameForVolumeMountPointW$FUNC
    );
    static final FunctionDescriptor GetVolumePathNamesForVolumeNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetVolumePathNamesForVolumeNameW$MH = RuntimeHelper.downcallHandle(
        "GetVolumePathNamesForVolumeNameW",
        constants$185.GetVolumePathNamesForVolumeNameW$FUNC
    );
    static final FunctionDescriptor CreateFile2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateFile2$MH = RuntimeHelper.downcallHandle(
        "CreateFile2",
        constants$185.CreateFile2$FUNC
    );
    static final FunctionDescriptor SetFileIoOverlappedRange$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetFileIoOverlappedRange$MH = RuntimeHelper.downcallHandle(
        "SetFileIoOverlappedRange",
        constants$185.SetFileIoOverlappedRange$FUNC
    );
    static final FunctionDescriptor GetCompressedFileSizeA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCompressedFileSizeA$MH = RuntimeHelper.downcallHandle(
        "GetCompressedFileSizeA",
        constants$185.GetCompressedFileSizeA$FUNC
    );
    static final FunctionDescriptor GetCompressedFileSizeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCompressedFileSizeW$MH = RuntimeHelper.downcallHandle(
        "GetCompressedFileSizeW",
        constants$185.GetCompressedFileSizeW$FUNC
    );
}


