// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$391 {

    static final FunctionDescriptor EnumFontFamiliesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesA$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesA",
        constants$391.EnumFontFamiliesA$FUNC
    );
    static final FunctionDescriptor EnumFontFamiliesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontFamiliesW$MH = RuntimeHelper.downcallHandle(
        "EnumFontFamiliesW",
        constants$391.EnumFontFamiliesW$FUNC
    );
    static final FunctionDescriptor EnumFontsA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontsA$MH = RuntimeHelper.downcallHandle(
        "EnumFontsA",
        constants$391.EnumFontsA$FUNC
    );
    static final FunctionDescriptor EnumFontsW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumFontsW$MH = RuntimeHelper.downcallHandle(
        "EnumFontsW",
        constants$391.EnumFontsW$FUNC
    );
    static final FunctionDescriptor EnumObjects$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle EnumObjects$MH = RuntimeHelper.downcallHandle(
        "EnumObjects",
        constants$391.EnumObjects$FUNC
    );
    static final FunctionDescriptor EqualRgn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle EqualRgn$MH = RuntimeHelper.downcallHandle(
        "EqualRgn",
        constants$391.EqualRgn$FUNC
    );
}


