// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$434 {

    static final FunctionDescriptor OffsetViewportOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OffsetViewportOrgEx$MH = RuntimeHelper.downcallHandle(
        "OffsetViewportOrgEx",
        constants$434.OffsetViewportOrgEx$FUNC
    );
    static final FunctionDescriptor OffsetWindowOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OffsetWindowOrgEx$MH = RuntimeHelper.downcallHandle(
        "OffsetWindowOrgEx",
        constants$434.OffsetWindowOrgEx$FUNC
    );
    static final FunctionDescriptor ScaleViewportExtEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ScaleViewportExtEx$MH = RuntimeHelper.downcallHandle(
        "ScaleViewportExtEx",
        constants$434.ScaleViewportExtEx$FUNC
    );
    static final FunctionDescriptor ScaleWindowExtEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ScaleWindowExtEx$MH = RuntimeHelper.downcallHandle(
        "ScaleWindowExtEx",
        constants$434.ScaleWindowExtEx$FUNC
    );
    static final FunctionDescriptor SetBitmapDimensionEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetBitmapDimensionEx$MH = RuntimeHelper.downcallHandle(
        "SetBitmapDimensionEx",
        constants$434.SetBitmapDimensionEx$FUNC
    );
    static final FunctionDescriptor SetBrushOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetBrushOrgEx$MH = RuntimeHelper.downcallHandle(
        "SetBrushOrgEx",
        constants$434.SetBrushOrgEx$FUNC
    );
}


