// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1274 {

    static final FunctionDescriptor ImmSimulateHotKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ImmSimulateHotKey$MH = RuntimeHelper.downcallHandle(
        "ImmSimulateHotKey",
        constants$1274.ImmSimulateHotKey$FUNC
    );
    static final FunctionDescriptor ImmCreateContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle ImmCreateContext$MH = RuntimeHelper.downcallHandle(
        "ImmCreateContext",
        constants$1274.ImmCreateContext$FUNC
    );
    static final FunctionDescriptor ImmDestroyContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmDestroyContext$MH = RuntimeHelper.downcallHandle(
        "ImmDestroyContext",
        constants$1274.ImmDestroyContext$FUNC
    );
    static final FunctionDescriptor ImmGetContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetContext$MH = RuntimeHelper.downcallHandle(
        "ImmGetContext",
        constants$1274.ImmGetContext$FUNC
    );
    static final FunctionDescriptor ImmReleaseContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmReleaseContext$MH = RuntimeHelper.downcallHandle(
        "ImmReleaseContext",
        constants$1274.ImmReleaseContext$FUNC
    );
    static final FunctionDescriptor ImmAssociateContext$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmAssociateContext$MH = RuntimeHelper.downcallHandle(
        "ImmAssociateContext",
        constants$1274.ImmAssociateContext$FUNC
    );
}


