// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$899 {

    static final  OfAddress __MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle __MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec$VH = constants$899.__MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec$LAYOUT.varHandle();
    static final MemorySegment __MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec$SEGMENT = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec", constants$899.__MIDL_itf_wtypes_0000_0001_v0_0_s_ifspec$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_DISK$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_DISK$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_DISK", constants$899.GUID_DEVINTERFACE_DISK$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_CDROM$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_CDROM$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_CDROM", constants$899.GUID_DEVINTERFACE_CDROM$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_PARTITION$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_PARTITION$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_PARTITION", constants$899.GUID_DEVINTERFACE_PARTITION$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_TAPE$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_TAPE$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_TAPE", constants$899.GUID_DEVINTERFACE_TAPE$LAYOUT);
    static final  GroupLayout GUID_DEVINTERFACE_WRITEONCEDISK$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment GUID_DEVINTERFACE_WRITEONCEDISK$SEGMENT = RuntimeHelper.lookupGlobalVariable("GUID_DEVINTERFACE_WRITEONCEDISK", constants$899.GUID_DEVINTERFACE_WRITEONCEDISK$LAYOUT);
}


