// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1224 {

    static final FunctionDescriptor VarPow$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarPow$MH = RuntimeHelper.downcallHandle(
        "VarPow",
        constants$1224.VarPow$FUNC
    );
    static final FunctionDescriptor VarSub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarSub$MH = RuntimeHelper.downcallHandle(
        "VarSub",
        constants$1224.VarSub$FUNC
    );
    static final FunctionDescriptor VarXor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarXor$MH = RuntimeHelper.downcallHandle(
        "VarXor",
        constants$1224.VarXor$FUNC
    );
    static final FunctionDescriptor VarAbs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarAbs$MH = RuntimeHelper.downcallHandle(
        "VarAbs",
        constants$1224.VarAbs$FUNC
    );
    static final FunctionDescriptor VarFix$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarFix$MH = RuntimeHelper.downcallHandle(
        "VarFix",
        constants$1224.VarFix$FUNC
    );
    static final FunctionDescriptor VarInt$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarInt$MH = RuntimeHelper.downcallHandle(
        "VarInt",
        constants$1224.VarInt$FUNC
    );
}


