// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1071 {

    static final FunctionDescriptor VARIANT_UserSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VARIANT_UserSize$MH = RuntimeHelper.downcallHandle(
        "VARIANT_UserSize",
        constants$1071.VARIANT_UserSize$FUNC
    );
    static final FunctionDescriptor VARIANT_UserMarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VARIANT_UserMarshal$MH = RuntimeHelper.downcallHandle(
        "VARIANT_UserMarshal",
        constants$1071.VARIANT_UserMarshal$FUNC
    );
    static final FunctionDescriptor VARIANT_UserUnmarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VARIANT_UserUnmarshal$MH = RuntimeHelper.downcallHandle(
        "VARIANT_UserUnmarshal",
        constants$1071.VARIANT_UserUnmarshal$FUNC
    );
    static final FunctionDescriptor VARIANT_UserFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VARIANT_UserFree$MH = RuntimeHelper.downcallHandle(
        "VARIANT_UserFree",
        constants$1071.VARIANT_UserFree$FUNC
    );
    static final FunctionDescriptor BSTR_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BSTR_UserSize64$MH = RuntimeHelper.downcallHandle(
        "BSTR_UserSize64",
        constants$1071.BSTR_UserSize64$FUNC
    );
    static final FunctionDescriptor BSTR_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BSTR_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "BSTR_UserMarshal64",
        constants$1071.BSTR_UserMarshal64$FUNC
    );
}


