// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$708 {

    static final FunctionDescriptor UuidCreateNil$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidCreateNil$MH = RuntimeHelper.downcallHandle(
        "UuidCreateNil",
        constants$708.UuidCreateNil$FUNC
    );
    static final FunctionDescriptor UuidEqual$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidEqual$MH = RuntimeHelper.downcallHandle(
        "UuidEqual",
        constants$708.UuidEqual$FUNC
    );
    static final FunctionDescriptor UuidHash$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidHash$MH = RuntimeHelper.downcallHandle(
        "UuidHash",
        constants$708.UuidHash$FUNC
    );
    static final FunctionDescriptor UuidIsNil$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UuidIsNil$MH = RuntimeHelper.downcallHandle(
        "UuidIsNil",
        constants$708.UuidIsNil$FUNC
    );
    static final FunctionDescriptor RpcEpRegisterNoReplaceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcEpRegisterNoReplaceA$MH = RuntimeHelper.downcallHandle(
        "RpcEpRegisterNoReplaceA",
        constants$708.RpcEpRegisterNoReplaceA$FUNC
    );
    static final FunctionDescriptor RpcEpRegisterNoReplaceW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcEpRegisterNoReplaceW$MH = RuntimeHelper.downcallHandle(
        "RpcEpRegisterNoReplaceW",
        constants$708.RpcEpRegisterNoReplaceW$FUNC
    );
}


