// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$628 {

    static final FunctionDescriptor RegQueryValueA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueA$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueA",
        constants$628.RegQueryValueA$FUNC
    );
    static final FunctionDescriptor RegQueryValueW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueW$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueW",
        constants$628.RegQueryValueW$FUNC
    );
    static final FunctionDescriptor RegQueryMultipleValuesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryMultipleValuesA$MH = RuntimeHelper.downcallHandle(
        "RegQueryMultipleValuesA",
        constants$628.RegQueryMultipleValuesA$FUNC
    );
    static final FunctionDescriptor RegQueryMultipleValuesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryMultipleValuesW$MH = RuntimeHelper.downcallHandle(
        "RegQueryMultipleValuesW",
        constants$628.RegQueryMultipleValuesW$FUNC
    );
    static final FunctionDescriptor RegQueryValueExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueExA$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueExA",
        constants$628.RegQueryValueExA$FUNC
    );
    static final FunctionDescriptor RegQueryValueExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RegQueryValueExW$MH = RuntimeHelper.downcallHandle(
        "RegQueryValueExW",
        constants$628.RegQueryValueExW$FUNC
    );
}


