// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1052 {

    static final FunctionDescriptor AsyncIAdviseSink2_Finish_OnLinkSrcChange_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AsyncIAdviseSink2_Finish_OnLinkSrcChange_Stub$MH = RuntimeHelper.downcallHandle(
        "AsyncIAdviseSink2_Finish_OnLinkSrcChange_Stub",
        constants$1052.AsyncIAdviseSink2_Finish_OnLinkSrcChange_Stub$FUNC
    );
    static final FunctionDescriptor IDataObject_GetData_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IDataObject_GetData_Proxy$MH = RuntimeHelper.downcallHandle(
        "IDataObject_GetData_Proxy",
        constants$1052.IDataObject_GetData_Proxy$FUNC
    );
    static final FunctionDescriptor IDataObject_GetData_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IDataObject_GetData_Stub$MH = RuntimeHelper.downcallHandle(
        "IDataObject_GetData_Stub",
        constants$1052.IDataObject_GetData_Stub$FUNC
    );
    static final FunctionDescriptor IDataObject_GetDataHere_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IDataObject_GetDataHere_Proxy$MH = RuntimeHelper.downcallHandle(
        "IDataObject_GetDataHere_Proxy",
        constants$1052.IDataObject_GetDataHere_Proxy$FUNC
    );
    static final FunctionDescriptor IDataObject_GetDataHere_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IDataObject_GetDataHere_Stub$MH = RuntimeHelper.downcallHandle(
        "IDataObject_GetDataHere_Stub",
        constants$1052.IDataObject_GetDataHere_Stub$FUNC
    );
    static final FunctionDescriptor IDataObject_SetData_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle IDataObject_SetData_Proxy$MH = RuntimeHelper.downcallHandle(
        "IDataObject_SetData_Proxy",
        constants$1052.IDataObject_SetData_Proxy$FUNC
    );
}


