// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$199 {

    static final FunctionDescriptor ImpersonateNamedPipeClient$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImpersonateNamedPipeClient$MH = RuntimeHelper.downcallHandle(
        "ImpersonateNamedPipeClient",
        constants$199.ImpersonateNamedPipeClient$FUNC
    );
    static final FunctionDescriptor GetNamedPipeInfo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetNamedPipeInfo$MH = RuntimeHelper.downcallHandle(
        "GetNamedPipeInfo",
        constants$199.GetNamedPipeInfo$FUNC
    );
    static final FunctionDescriptor GetNamedPipeHandleStateW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetNamedPipeHandleStateW$MH = RuntimeHelper.downcallHandle(
        "GetNamedPipeHandleStateW",
        constants$199.GetNamedPipeHandleStateW$FUNC
    );
    static final FunctionDescriptor CallNamedPipeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CallNamedPipeW$MH = RuntimeHelper.downcallHandle(
        "CallNamedPipeW",
        constants$199.CallNamedPipeW$FUNC
    );
    static final FunctionDescriptor QueryPerformanceCounter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryPerformanceCounter$MH = RuntimeHelper.downcallHandle(
        "QueryPerformanceCounter",
        constants$199.QueryPerformanceCounter$FUNC
    );
    static final FunctionDescriptor QueryPerformanceFrequency$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryPerformanceFrequency$MH = RuntimeHelper.downcallHandle(
        "QueryPerformanceFrequency",
        constants$199.QueryPerformanceFrequency$FUNC
    );
}


