// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1600 {

    static final MemorySegment SERVICE_TYPE_VALUE_OBJECTID$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ObjectId");
}


