// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$647 {

    static final FunctionDescriptor DdeEnableCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeEnableCallback$MH = RuntimeHelper.downcallHandle(
        "DdeEnableCallback",
        constants$647.DdeEnableCallback$FUNC
    );
    static final FunctionDescriptor DdeImpersonateClient$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdeImpersonateClient$MH = RuntimeHelper.downcallHandle(
        "DdeImpersonateClient",
        constants$647.DdeImpersonateClient$FUNC
    );
    static final FunctionDescriptor DdeNameService$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeNameService$MH = RuntimeHelper.downcallHandle(
        "DdeNameService",
        constants$647.DdeNameService$FUNC
    );
    static final FunctionDescriptor DdeClientTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DdeClientTransaction$MH = RuntimeHelper.downcallHandle(
        "DdeClientTransaction",
        constants$647.DdeClientTransaction$FUNC
    );
    static final FunctionDescriptor DdeCreateDataHandle$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeCreateDataHandle$MH = RuntimeHelper.downcallHandle(
        "DdeCreateDataHandle",
        constants$647.DdeCreateDataHandle$FUNC
    );
    static final FunctionDescriptor DdeAddData$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle DdeAddData$MH = RuntimeHelper.downcallHandle(
        "DdeAddData",
        constants$647.DdeAddData$FUNC
    );
}


