// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$417 {

    static final FunctionDescriptor SetSystemPaletteUse$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetSystemPaletteUse$MH = RuntimeHelper.downcallHandle(
        "SetSystemPaletteUse",
        constants$417.SetSystemPaletteUse$FUNC
    );
    static final FunctionDescriptor SetTextCharacterExtra$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetTextCharacterExtra$MH = RuntimeHelper.downcallHandle(
        "SetTextCharacterExtra",
        constants$417.SetTextCharacterExtra$FUNC
    );
    static final FunctionDescriptor SetTextColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetTextColor$MH = RuntimeHelper.downcallHandle(
        "SetTextColor",
        constants$417.SetTextColor$FUNC
    );
    static final FunctionDescriptor SetTextAlign$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetTextAlign$MH = RuntimeHelper.downcallHandle(
        "SetTextAlign",
        constants$417.SetTextAlign$FUNC
    );
    static final FunctionDescriptor SetTextJustification$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetTextJustification$MH = RuntimeHelper.downcallHandle(
        "SetTextJustification",
        constants$417.SetTextJustification$FUNC
    );
    static final FunctionDescriptor UpdateColors$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UpdateColors$MH = RuntimeHelper.downcallHandle(
        "UpdateColors",
        constants$417.UpdateColors$FUNC
    );
}


