// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$236 {

    static final FunctionDescriptor GetOsSafeBootMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetOsSafeBootMode$MH = RuntimeHelper.downcallHandle(
        "GetOsSafeBootMode",
        constants$236.GetOsSafeBootMode$FUNC
    );
    static final FunctionDescriptor EnumSystemFirmwareTables$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumSystemFirmwareTables$MH = RuntimeHelper.downcallHandle(
        "EnumSystemFirmwareTables",
        constants$236.EnumSystemFirmwareTables$FUNC
    );
    static final FunctionDescriptor GetSystemFirmwareTable$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetSystemFirmwareTable$MH = RuntimeHelper.downcallHandle(
        "GetSystemFirmwareTable",
        constants$236.GetSystemFirmwareTable$FUNC
    );
    static final FunctionDescriptor DnsHostnameToComputerNameExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DnsHostnameToComputerNameExW$MH = RuntimeHelper.downcallHandle(
        "DnsHostnameToComputerNameExW",
        constants$236.DnsHostnameToComputerNameExW$FUNC
    );
    static final FunctionDescriptor GetPhysicallyInstalledSystemMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPhysicallyInstalledSystemMemory$MH = RuntimeHelper.downcallHandle(
        "GetPhysicallyInstalledSystemMemory",
        constants$236.GetPhysicallyInstalledSystemMemory$FUNC
    );
    static final FunctionDescriptor SetComputerNameEx2W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetComputerNameEx2W$MH = RuntimeHelper.downcallHandle(
        "SetComputerNameEx2W",
        constants$236.SetComputerNameEx2W$FUNC
    );
}


