// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1294 {

    static final FunctionDescriptor WSAConnectByNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WSAConnectByNameW$MH = RuntimeHelper.downcallHandle(
        "WSAConnectByNameW",
        constants$1294.WSAConnectByNameW$FUNC
    );
    static final FunctionDescriptor WSAConnectByNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WSAConnectByNameA$MH = RuntimeHelper.downcallHandle(
        "WSAConnectByNameA",
        constants$1294.WSAConnectByNameA$FUNC
    );
    static final FunctionDescriptor WSAConnectByList$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WSAConnectByList$MH = RuntimeHelper.downcallHandle(
        "WSAConnectByList",
        constants$1294.WSAConnectByList$FUNC
    );
    static final FunctionDescriptor WSACreateEvent$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle WSACreateEvent$MH = RuntimeHelper.downcallHandle(
        "WSACreateEvent",
        constants$1294.WSACreateEvent$FUNC
    );
    static final FunctionDescriptor WSADuplicateSocketA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WSADuplicateSocketA$MH = RuntimeHelper.downcallHandle(
        "WSADuplicateSocketA",
        constants$1294.WSADuplicateSocketA$FUNC
    );
    static final FunctionDescriptor WSADuplicateSocketW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WSADuplicateSocketW$MH = RuntimeHelper.downcallHandle(
        "WSADuplicateSocketW",
        constants$1294.WSADuplicateSocketW$FUNC
    );
}


