// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$732 {

    static final FunctionDescriptor I_RpcRecordCalloutFailure$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcRecordCalloutFailure$MH = RuntimeHelper.downcallHandle(
        "I_RpcRecordCalloutFailure",
        constants$732.I_RpcRecordCalloutFailure$FUNC
    );
    static final FunctionDescriptor I_RpcMgmtEnableDedicatedThreadPool$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle I_RpcMgmtEnableDedicatedThreadPool$MH = RuntimeHelper.downcallHandle(
        "I_RpcMgmtEnableDedicatedThreadPool",
        constants$732.I_RpcMgmtEnableDedicatedThreadPool$FUNC
    );
    static final FunctionDescriptor I_RpcGetDefaultSD$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcGetDefaultSD$MH = RuntimeHelper.downcallHandle(
        "I_RpcGetDefaultSD",
        constants$732.I_RpcGetDefaultSD$FUNC
    );
    static final FunctionDescriptor I_RpcOpenClientProcess$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcOpenClientProcess$MH = RuntimeHelper.downcallHandle(
        "I_RpcOpenClientProcess",
        constants$732.I_RpcOpenClientProcess$FUNC
    );
    static final FunctionDescriptor I_RpcBindingIsServerLocal$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle I_RpcBindingIsServerLocal$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingIsServerLocal",
        constants$732.I_RpcBindingIsServerLocal$FUNC
    );
    static final FunctionDescriptor I_RpcBindingSetPrivateOption$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle I_RpcBindingSetPrivateOption$MH = RuntimeHelper.downcallHandle(
        "I_RpcBindingSetPrivateOption",
        constants$732.I_RpcBindingSetPrivateOption$FUNC
    );
}


