// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1337 {

    static final MemoryAddress HBMMENU_POPUP_MAXIMIZE$ADDR = MemoryAddress.ofLong(10L);
    static final MemoryAddress HBMMENU_POPUP_MINIMIZE$ADDR = MemoryAddress.ofLong(11L);
    static final MemoryAddress IDC_ARROW$ADDR = MemoryAddress.ofLong(32512L);
    static final MemoryAddress IDC_IBEAM$ADDR = MemoryAddress.ofLong(32513L);
    static final MemoryAddress IDC_WAIT$ADDR = MemoryAddress.ofLong(32514L);
    static final MemoryAddress IDC_CROSS$ADDR = MemoryAddress.ofLong(32515L);
}


