// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1125 {

    static final  GroupLayout CLSID_StdURLMoniker$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_StdURLMoniker$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_StdURLMoniker", constants$1125.CLSID_StdURLMoniker$LAYOUT);
    static final  GroupLayout CLSID_HttpProtocol$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_HttpProtocol$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_HttpProtocol", constants$1125.CLSID_HttpProtocol$LAYOUT);
    static final  GroupLayout CLSID_FtpProtocol$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_FtpProtocol$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_FtpProtocol", constants$1125.CLSID_FtpProtocol$LAYOUT);
    static final  GroupLayout CLSID_GopherProtocol$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_GopherProtocol$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_GopherProtocol", constants$1125.CLSID_GopherProtocol$LAYOUT);
    static final  GroupLayout CLSID_HttpSProtocol$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_HttpSProtocol$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_HttpSProtocol", constants$1125.CLSID_HttpSProtocol$LAYOUT);
    static final  GroupLayout CLSID_FileProtocol$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_FileProtocol$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_FileProtocol", constants$1125.CLSID_FileProtocol$LAYOUT);
}


