// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$204 {

    static final FunctionDescriptor GetOverlappedResultEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetOverlappedResultEx$MH = RuntimeHelper.downcallHandle(
        "GetOverlappedResultEx",
        constants$204.GetOverlappedResultEx$FUNC
    );
    static final FunctionDescriptor CancelSynchronousIo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CancelSynchronousIo$MH = RuntimeHelper.downcallHandle(
        "CancelSynchronousIo",
        constants$204.CancelSynchronousIo$FUNC
    );
    static final FunctionDescriptor InitializeSRWLock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle InitializeSRWLock$MH = RuntimeHelper.downcallHandle(
        "InitializeSRWLock",
        constants$204.InitializeSRWLock$FUNC
    );
    static final FunctionDescriptor ReleaseSRWLockExclusive$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReleaseSRWLockExclusive$MH = RuntimeHelper.downcallHandle(
        "ReleaseSRWLockExclusive",
        constants$204.ReleaseSRWLockExclusive$FUNC
    );
    static final FunctionDescriptor ReleaseSRWLockShared$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ReleaseSRWLockShared$MH = RuntimeHelper.downcallHandle(
        "ReleaseSRWLockShared",
        constants$204.ReleaseSRWLockShared$FUNC
    );
    static final FunctionDescriptor AcquireSRWLockExclusive$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AcquireSRWLockExclusive$MH = RuntimeHelper.downcallHandle(
        "AcquireSRWLockExclusive",
        constants$204.AcquireSRWLockExclusive$FUNC
    );
}


