// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$58 {

    static final FunctionDescriptor LongToHandle$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle LongToHandle$MH = RuntimeHelper.downcallHandle(
        "LongToHandle",
        constants$58.LongToHandle$FUNC
    );
    static final FunctionDescriptor PtrToUlong$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PtrToUlong$MH = RuntimeHelper.downcallHandle(
        "PtrToUlong",
        constants$58.PtrToUlong$FUNC
    );
    static final FunctionDescriptor PtrToUint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PtrToUint$MH = RuntimeHelper.downcallHandle(
        "PtrToUint",
        constants$58.PtrToUint$FUNC
    );
    static final FunctionDescriptor PtrToUshort$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PtrToUshort$MH = RuntimeHelper.downcallHandle(
        "PtrToUshort",
        constants$58.PtrToUshort$FUNC
    );
    static final FunctionDescriptor PtrToLong$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PtrToLong$MH = RuntimeHelper.downcallHandle(
        "PtrToLong",
        constants$58.PtrToLong$FUNC
    );
    static final FunctionDescriptor PtrToInt$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PtrToInt$MH = RuntimeHelper.downcallHandle(
        "PtrToInt",
        constants$58.PtrToInt$FUNC
    );
}


