// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1038 {

    static final FunctionDescriptor FLAG_STGMEDIUM_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FLAG_STGMEDIUM_UserFree64$MH = RuntimeHelper.downcallHandle(
        "FLAG_STGMEDIUM_UserFree64",
        constants$1038.FLAG_STGMEDIUM_UserFree64$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserSize64$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserSize64",
        constants$1038.HBITMAP_UserSize64$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserMarshal64",
        constants$1038.HBITMAP_UserMarshal64$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserUnmarshal64",
        constants$1038.HBITMAP_UserUnmarshal64$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserFree64$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserFree64",
        constants$1038.HBITMAP_UserFree64$FUNC
    );
    static final FunctionDescriptor HDC_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserSize64$MH = RuntimeHelper.downcallHandle(
        "HDC_UserSize64",
        constants$1038.HDC_UserSize64$FUNC
    );
}


