// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1187 {

    static final FunctionDescriptor VarUI1FromDec$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarUI1FromDec$MH = RuntimeHelper.downcallHandle(
        "VarUI1FromDec",
        constants$1187.VarUI1FromDec$FUNC
    );
    static final FunctionDescriptor VarI2FromUI1$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarI2FromUI1$MH = RuntimeHelper.downcallHandle(
        "VarI2FromUI1",
        constants$1187.VarI2FromUI1$FUNC
    );
    static final FunctionDescriptor VarI2FromI4$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarI2FromI4$MH = RuntimeHelper.downcallHandle(
        "VarI2FromI4",
        constants$1187.VarI2FromI4$FUNC
    );
    static final FunctionDescriptor VarI2FromI8$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarI2FromI8$MH = RuntimeHelper.downcallHandle(
        "VarI2FromI8",
        constants$1187.VarI2FromI8$FUNC
    );
    static final FunctionDescriptor VarI2FromR4$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarI2FromR4$MH = RuntimeHelper.downcallHandle(
        "VarI2FromR4",
        constants$1187.VarI2FromR4$FUNC
    );
    static final FunctionDescriptor VarI2FromR8$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarI2FromR8$MH = RuntimeHelper.downcallHandle(
        "VarI2FromR8",
        constants$1187.VarI2FromR8$FUNC
    );
}


