// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1062 {

    static final FunctionDescriptor ITypeInfo_LocalReleaseTypeAttr_Stub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_LocalReleaseTypeAttr_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_LocalReleaseTypeAttr_Stub",
        constants$1062.ITypeInfo_LocalReleaseTypeAttr_Stub$FUNC
    );
    static final FunctionDescriptor ITypeInfo_LocalReleaseFuncDesc_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_LocalReleaseFuncDesc_Proxy$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_LocalReleaseFuncDesc_Proxy",
        constants$1062.ITypeInfo_LocalReleaseFuncDesc_Proxy$FUNC
    );
    static final FunctionDescriptor ITypeInfo_LocalReleaseFuncDesc_Stub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_LocalReleaseFuncDesc_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_LocalReleaseFuncDesc_Stub",
        constants$1062.ITypeInfo_LocalReleaseFuncDesc_Stub$FUNC
    );
    static final FunctionDescriptor ITypeInfo_LocalReleaseVarDesc_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_LocalReleaseVarDesc_Proxy$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_LocalReleaseVarDesc_Proxy",
        constants$1062.ITypeInfo_LocalReleaseVarDesc_Proxy$FUNC
    );
    static final FunctionDescriptor ITypeInfo_LocalReleaseVarDesc_Stub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_LocalReleaseVarDesc_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_LocalReleaseVarDesc_Stub",
        constants$1062.ITypeInfo_LocalReleaseVarDesc_Stub$FUNC
    );
    static final  GroupLayout IID_ITypeInfo2$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_ITypeInfo2$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_ITypeInfo2", constants$1062.IID_ITypeInfo2$LAYOUT);
}


