// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$663 {

    static final FunctionDescriptor TIMECALLBACK$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle TIMECALLBACK$MH = RuntimeHelper.downcallHandle(
        constants$663.TIMECALLBACK$FUNC
    );
    static final FunctionDescriptor LPTIMECALLBACK$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle LPTIMECALLBACK$MH = RuntimeHelper.downcallHandle(
        constants$663.LPTIMECALLBACK$FUNC
    );
    static final FunctionDescriptor timeSetEvent$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle timeSetEvent$MH = RuntimeHelper.downcallHandle(
        "timeSetEvent",
        constants$663.timeSetEvent$FUNC
    );
    static final FunctionDescriptor timeKillEvent$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle timeKillEvent$MH = RuntimeHelper.downcallHandle(
        "timeKillEvent",
        constants$663.timeKillEvent$FUNC
    );
    static final FunctionDescriptor sndPlaySoundA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle sndPlaySoundA$MH = RuntimeHelper.downcallHandle(
        "sndPlaySoundA",
        constants$663.sndPlaySoundA$FUNC
    );
}


