// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$240 {

    static final FunctionDescriptor CreateFileMappingW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateFileMappingW$MH = RuntimeHelper.downcallHandle(
        "CreateFileMappingW",
        constants$240.CreateFileMappingW$FUNC
    );
    static final FunctionDescriptor OpenFileMappingW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenFileMappingW$MH = RuntimeHelper.downcallHandle(
        "OpenFileMappingW",
        constants$240.OpenFileMappingW$FUNC
    );
    static final FunctionDescriptor MapViewOfFile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle MapViewOfFile$MH = RuntimeHelper.downcallHandle(
        "MapViewOfFile",
        constants$240.MapViewOfFile$FUNC
    );
    static final FunctionDescriptor MapViewOfFileEx$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MapViewOfFileEx$MH = RuntimeHelper.downcallHandle(
        "MapViewOfFileEx",
        constants$240.MapViewOfFileEx$FUNC
    );
    static final FunctionDescriptor VirtualFreeEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle VirtualFreeEx$MH = RuntimeHelper.downcallHandle(
        "VirtualFreeEx",
        constants$240.VirtualFreeEx$FUNC
    );
    static final FunctionDescriptor FlushViewOfFile$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle FlushViewOfFile$MH = RuntimeHelper.downcallHandle(
        "FlushViewOfFile",
        constants$240.FlushViewOfFile$FUNC
    );
}


