// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$46 {

    static final FunctionDescriptor _iswalnum_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswalnum_l$MH = RuntimeHelper.downcallHandle(
        "_iswalnum_l",
        constants$46._iswalnum_l$FUNC
    );
    static final FunctionDescriptor _iswalpha_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswalpha_l$MH = RuntimeHelper.downcallHandle(
        "_iswalpha_l",
        constants$46._iswalpha_l$FUNC
    );
    static final FunctionDescriptor _iswblank_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswblank_l$MH = RuntimeHelper.downcallHandle(
        "_iswblank_l",
        constants$46._iswblank_l$FUNC
    );
    static final FunctionDescriptor _iswcntrl_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswcntrl_l$MH = RuntimeHelper.downcallHandle(
        "_iswcntrl_l",
        constants$46._iswcntrl_l$FUNC
    );
    static final FunctionDescriptor _iswdigit_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswdigit_l$MH = RuntimeHelper.downcallHandle(
        "_iswdigit_l",
        constants$46._iswdigit_l$FUNC
    );
    static final FunctionDescriptor _iswgraph_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _iswgraph_l$MH = RuntimeHelper.downcallHandle(
        "_iswgraph_l",
        constants$46._iswgraph_l$FUNC
    );
}


