// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$696 {

    static final FunctionDescriptor RpcServerUseProtseqW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqW$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqW",
        constants$696.RpcServerUseProtseqW$FUNC
    );
    static final FunctionDescriptor RpcServerUseProtseqExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqExW$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqExW",
        constants$696.RpcServerUseProtseqExW$FUNC
    );
    static final FunctionDescriptor RpcServerUseProtseqEpA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqEpA$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqEpA",
        constants$696.RpcServerUseProtseqEpA$FUNC
    );
    static final FunctionDescriptor RpcServerUseProtseqEpExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqEpExA$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqEpExA",
        constants$696.RpcServerUseProtseqEpExA$FUNC
    );
    static final FunctionDescriptor RpcServerUseProtseqEpW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqEpW$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqEpW",
        constants$696.RpcServerUseProtseqEpW$FUNC
    );
    static final FunctionDescriptor RpcServerUseProtseqEpExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcServerUseProtseqEpExW$MH = RuntimeHelper.downcallHandle(
        "RpcServerUseProtseqEpExW",
        constants$696.RpcServerUseProtseqEpExW$FUNC
    );
}


