// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$878 {

    static final FunctionDescriptor NdrComplexArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrComplexArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrComplexArrayFree",
        constants$878.NdrComplexArrayFree$FUNC
    );
    static final FunctionDescriptor NdrEncapsulatedUnionFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrEncapsulatedUnionFree$MH = RuntimeHelper.downcallHandle(
        "NdrEncapsulatedUnionFree",
        constants$878.NdrEncapsulatedUnionFree$FUNC
    );
    static final FunctionDescriptor NdrNonEncapsulatedUnionFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrNonEncapsulatedUnionFree$MH = RuntimeHelper.downcallHandle(
        "NdrNonEncapsulatedUnionFree",
        constants$878.NdrNonEncapsulatedUnionFree$FUNC
    );
    static final FunctionDescriptor NdrByteCountPointerFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrByteCountPointerFree$MH = RuntimeHelper.downcallHandle(
        "NdrByteCountPointerFree",
        constants$878.NdrByteCountPointerFree$FUNC
    );
    static final FunctionDescriptor NdrXmitOrRepAsFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrXmitOrRepAsFree$MH = RuntimeHelper.downcallHandle(
        "NdrXmitOrRepAsFree",
        constants$878.NdrXmitOrRepAsFree$FUNC
    );
    static final FunctionDescriptor NdrUserMarshalFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrUserMarshalFree$MH = RuntimeHelper.downcallHandle(
        "NdrUserMarshalFree",
        constants$878.NdrUserMarshalFree$FUNC
    );
}


