// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$273 {

    static final FunctionDescriptor AddResourceAttributeAce$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddResourceAttributeAce$MH = RuntimeHelper.downcallHandle(
        "AddResourceAttributeAce",
        constants$273.AddResourceAttributeAce$FUNC
    );
    static final FunctionDescriptor AddScopedPolicyIDAce$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddScopedPolicyIDAce$MH = RuntimeHelper.downcallHandle(
        "AddScopedPolicyIDAce",
        constants$273.AddScopedPolicyIDAce$FUNC
    );
    static final FunctionDescriptor AdjustTokenGroups$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AdjustTokenGroups$MH = RuntimeHelper.downcallHandle(
        "AdjustTokenGroups",
        constants$273.AdjustTokenGroups$FUNC
    );
    static final FunctionDescriptor AdjustTokenPrivileges$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AdjustTokenPrivileges$MH = RuntimeHelper.downcallHandle(
        "AdjustTokenPrivileges",
        constants$273.AdjustTokenPrivileges$FUNC
    );
    static final FunctionDescriptor AllocateAndInitializeSid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AllocateAndInitializeSid$MH = RuntimeHelper.downcallHandle(
        "AllocateAndInitializeSid",
        constants$273.AllocateAndInitializeSid$FUNC
    );
    static final FunctionDescriptor AllocateLocallyUniqueId$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AllocateLocallyUniqueId$MH = RuntimeHelper.downcallHandle(
        "AllocateLocallyUniqueId",
        constants$273.AllocateLocallyUniqueId$FUNC
    );
}


