// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$982 {

    static final  GroupLayout CLSID_CCDScrollBar$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDScrollBar$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDScrollBar", constants$982.CLSID_CCDScrollBar$LAYOUT);
    static final  GroupLayout CLSID_CCDGroupBox$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDGroupBox$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDGroupBox", constants$982.CLSID_CCDGroupBox$LAYOUT);
    static final  GroupLayout CLSID_CCDGeneralPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDGeneralPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDGeneralPropertyPage", constants$982.CLSID_CCDGeneralPropertyPage$LAYOUT);
    static final  GroupLayout CLSID_CCDGenericPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDGenericPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDGenericPropertyPage", constants$982.CLSID_CCDGenericPropertyPage$LAYOUT);
    static final  GroupLayout CLSID_CCDFontPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDFontPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDFontPropertyPage", constants$982.CLSID_CCDFontPropertyPage$LAYOUT);
    static final  GroupLayout CLSID_CCDColorPropertyPage$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment CLSID_CCDColorPropertyPage$SEGMENT = RuntimeHelper.lookupGlobalVariable("CLSID_CCDColorPropertyPage", constants$982.CLSID_CCDColorPropertyPage$LAYOUT);
}


