// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1338 {

    static final MemoryAddress IDC_UPARROW$ADDR = MemoryAddress.ofLong(32516L);
    static final MemoryAddress IDC_SIZE$ADDR = MemoryAddress.ofLong(32640L);
    static final MemoryAddress IDC_ICON$ADDR = MemoryAddress.ofLong(32641L);
    static final MemoryAddress IDC_SIZENWSE$ADDR = MemoryAddress.ofLong(32642L);
    static final MemoryAddress IDC_SIZENESW$ADDR = MemoryAddress.ofLong(32643L);
    static final MemoryAddress IDC_SIZEWE$ADDR = MemoryAddress.ofLong(32644L);
}


