// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$950 {

    static final  GroupLayout IID_IUnknown$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IUnknown$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IUnknown", constants$950.IID_IUnknown$LAYOUT);
    static final FunctionDescriptor IUnknown_QueryInterface_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IUnknown_QueryInterface_Proxy$MH = RuntimeHelper.downcallHandle(
        "IUnknown_QueryInterface_Proxy",
        constants$950.IUnknown_QueryInterface_Proxy$FUNC
    );
    static final FunctionDescriptor IUnknown_QueryInterface_Stub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IUnknown_QueryInterface_Stub$MH = RuntimeHelper.downcallHandle(
        "IUnknown_QueryInterface_Stub",
        constants$950.IUnknown_QueryInterface_Stub$FUNC
    );
    static final FunctionDescriptor IUnknown_AddRef_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IUnknown_AddRef_Proxy$MH = RuntimeHelper.downcallHandle(
        "IUnknown_AddRef_Proxy",
        constants$950.IUnknown_AddRef_Proxy$FUNC
    );
    static final FunctionDescriptor IUnknown_AddRef_Stub$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IUnknown_AddRef_Stub$MH = RuntimeHelper.downcallHandle(
        "IUnknown_AddRef_Stub",
        constants$950.IUnknown_AddRef_Stub$FUNC
    );
    static final FunctionDescriptor IUnknown_Release_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle IUnknown_Release_Proxy$MH = RuntimeHelper.downcallHandle(
        "IUnknown_Release_Proxy",
        constants$950.IUnknown_Release_Proxy$FUNC
    );
}


