// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1198 {

    static final FunctionDescriptor VarR8FromDate$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromDate$MH = RuntimeHelper.downcallHandle(
        "VarR8FromDate",
        constants$1198.VarR8FromDate$FUNC
    );
    static final FunctionDescriptor VarR8FromStr$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromStr$MH = RuntimeHelper.downcallHandle(
        "VarR8FromStr",
        constants$1198.VarR8FromStr$FUNC
    );
    static final FunctionDescriptor VarR8FromDisp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromDisp$MH = RuntimeHelper.downcallHandle(
        "VarR8FromDisp",
        constants$1198.VarR8FromDisp$FUNC
    );
    static final FunctionDescriptor VarR8FromBool$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromBool$MH = RuntimeHelper.downcallHandle(
        "VarR8FromBool",
        constants$1198.VarR8FromBool$FUNC
    );
    static final FunctionDescriptor VarR8FromI1$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromI1$MH = RuntimeHelper.downcallHandle(
        "VarR8FromI1",
        constants$1198.VarR8FromI1$FUNC
    );
    static final FunctionDescriptor VarR8FromUI2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VarR8FromUI2$MH = RuntimeHelper.downcallHandle(
        "VarR8FromUI2",
        constants$1198.VarR8FromUI2$FUNC
    );
}


