// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$555 {

    static final FunctionDescriptor EnumDisplaySettingsExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumDisplaySettingsExA$MH = RuntimeHelper.downcallHandle(
        "EnumDisplaySettingsExA",
        constants$555.EnumDisplaySettingsExA$FUNC
    );
    static final FunctionDescriptor EnumDisplaySettingsExW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumDisplaySettingsExW$MH = RuntimeHelper.downcallHandle(
        "EnumDisplaySettingsExW",
        constants$555.EnumDisplaySettingsExW$FUNC
    );
    static final FunctionDescriptor EnumDisplayDevicesA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumDisplayDevicesA$MH = RuntimeHelper.downcallHandle(
        "EnumDisplayDevicesA",
        constants$555.EnumDisplayDevicesA$FUNC
    );
    static final FunctionDescriptor EnumDisplayDevicesW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumDisplayDevicesW$MH = RuntimeHelper.downcallHandle(
        "EnumDisplayDevicesW",
        constants$555.EnumDisplayDevicesW$FUNC
    );
    static final FunctionDescriptor GetDisplayConfigBufferSizes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDisplayConfigBufferSizes$MH = RuntimeHelper.downcallHandle(
        "GetDisplayConfigBufferSizes",
        constants$555.GetDisplayConfigBufferSizes$FUNC
    );
    static final FunctionDescriptor SetDisplayConfig$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetDisplayConfig$MH = RuntimeHelper.downcallHandle(
        "SetDisplayConfig",
        constants$555.SetDisplayConfig$FUNC
    );
}


