// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$642 {

    static final FunctionDescriptor WNetGetProviderNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetProviderNameW$MH = RuntimeHelper.downcallHandle(
        "WNetGetProviderNameW",
        constants$642.WNetGetProviderNameW$FUNC
    );
    static final FunctionDescriptor WNetGetNetworkInformationA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetNetworkInformationA$MH = RuntimeHelper.downcallHandle(
        "WNetGetNetworkInformationA",
        constants$642.WNetGetNetworkInformationA$FUNC
    );
    static final FunctionDescriptor WNetGetNetworkInformationW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WNetGetNetworkInformationW$MH = RuntimeHelper.downcallHandle(
        "WNetGetNetworkInformationW",
        constants$642.WNetGetNetworkInformationW$FUNC
    );
    static final FunctionDescriptor WNetGetLastErrorA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetGetLastErrorA$MH = RuntimeHelper.downcallHandle(
        "WNetGetLastErrorA",
        constants$642.WNetGetLastErrorA$FUNC
    );
    static final FunctionDescriptor WNetGetLastErrorW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetGetLastErrorW$MH = RuntimeHelper.downcallHandle(
        "WNetGetLastErrorW",
        constants$642.WNetGetLastErrorW$FUNC
    );
    static final FunctionDescriptor MultinetGetConnectionPerformanceA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MultinetGetConnectionPerformanceA$MH = RuntimeHelper.downcallHandle(
        "MultinetGetConnectionPerformanceA",
        constants$642.MultinetGetConnectionPerformanceA$FUNC
    );
}


