// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$67 {

    static final FunctionDescriptor _wcstok$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcstok$MH = RuntimeHelper.downcallHandle(
        "_wcstok",
        constants$67._wcstok$FUNC
    );
    static final FunctionDescriptor _wcserror$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _wcserror$MH = RuntimeHelper.downcallHandle(
        "_wcserror",
        constants$67._wcserror$FUNC
    );
    static final FunctionDescriptor _wcserror_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _wcserror_s$MH = RuntimeHelper.downcallHandle(
        "_wcserror_s",
        constants$67._wcserror_s$FUNC
    );
    static final FunctionDescriptor __wcserror$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __wcserror$MH = RuntimeHelper.downcallHandle(
        "__wcserror",
        constants$67.__wcserror$FUNC
    );
    static final FunctionDescriptor __wcserror_s$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __wcserror_s$MH = RuntimeHelper.downcallHandle(
        "__wcserror_s",
        constants$67.__wcserror_s$FUNC
    );
    static final FunctionDescriptor _wcsicmp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _wcsicmp$MH = RuntimeHelper.downcallHandle(
        "_wcsicmp",
        constants$67._wcsicmp$FUNC
    );
}


