// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$486 {

    static final FunctionDescriptor GetPriorityClipboardFormat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetPriorityClipboardFormat$MH = RuntimeHelper.downcallHandle(
        "GetPriorityClipboardFormat",
        constants$486.GetPriorityClipboardFormat$FUNC
    );
    static final FunctionDescriptor GetOpenClipboardWindow$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle GetOpenClipboardWindow$MH = RuntimeHelper.downcallHandle(
        "GetOpenClipboardWindow",
        constants$486.GetOpenClipboardWindow$FUNC
    );
    static final FunctionDescriptor AddClipboardFormatListener$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle AddClipboardFormatListener$MH = RuntimeHelper.downcallHandle(
        "AddClipboardFormatListener",
        constants$486.AddClipboardFormatListener$FUNC
    );
    static final FunctionDescriptor RemoveClipboardFormatListener$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RemoveClipboardFormatListener$MH = RuntimeHelper.downcallHandle(
        "RemoveClipboardFormatListener",
        constants$486.RemoveClipboardFormatListener$FUNC
    );
    static final FunctionDescriptor GetUpdatedClipboardFormats$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetUpdatedClipboardFormats$MH = RuntimeHelper.downcallHandle(
        "GetUpdatedClipboardFormats",
        constants$486.GetUpdatedClipboardFormats$FUNC
    );
    static final FunctionDescriptor CharToOemA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CharToOemA$MH = RuntimeHelper.downcallHandle(
        "CharToOemA",
        constants$486.CharToOemA$FUNC
    );
}


