// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$337 {

    static final FunctionDescriptor ReOpenFile$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ReOpenFile$MH = RuntimeHelper.downcallHandle(
        "ReOpenFile",
        constants$337.ReOpenFile$FUNC
    );
    static final FunctionDescriptor SetFileAttributesTransactedA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetFileAttributesTransactedA$MH = RuntimeHelper.downcallHandle(
        "SetFileAttributesTransactedA",
        constants$337.SetFileAttributesTransactedA$FUNC
    );
    static final FunctionDescriptor SetFileAttributesTransactedW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetFileAttributesTransactedW$MH = RuntimeHelper.downcallHandle(
        "SetFileAttributesTransactedW",
        constants$337.SetFileAttributesTransactedW$FUNC
    );
    static final FunctionDescriptor GetFileAttributesTransactedA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesTransactedA$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesTransactedA",
        constants$337.GetFileAttributesTransactedA$FUNC
    );
    static final FunctionDescriptor GetFileAttributesTransactedW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileAttributesTransactedW$MH = RuntimeHelper.downcallHandle(
        "GetFileAttributesTransactedW",
        constants$337.GetFileAttributesTransactedW$FUNC
    );
    static final FunctionDescriptor GetCompressedFileSizeTransactedA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCompressedFileSizeTransactedA$MH = RuntimeHelper.downcallHandle(
        "GetCompressedFileSizeTransactedA",
        constants$337.GetCompressedFileSizeTransactedA$FUNC
    );
}


