// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$791 {

    static final FunctionDescriptor CryptMsgVerifyCountersignatureEncoded$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgVerifyCountersignatureEncoded$MH = RuntimeHelper.downcallHandle(
        "CryptMsgVerifyCountersignatureEncoded",
        constants$791.CryptMsgVerifyCountersignatureEncoded$FUNC
    );
    static final FunctionDescriptor CryptMsgVerifyCountersignatureEncodedEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgVerifyCountersignatureEncodedEx$MH = RuntimeHelper.downcallHandle(
        "CryptMsgVerifyCountersignatureEncodedEx",
        constants$791.CryptMsgVerifyCountersignatureEncodedEx$FUNC
    );
    static final FunctionDescriptor CryptMsgCountersign$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgCountersign$MH = RuntimeHelper.downcallHandle(
        "CryptMsgCountersign",
        constants$791.CryptMsgCountersign$FUNC
    );
    static final FunctionDescriptor CryptMsgCountersignEncoded$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CryptMsgCountersignEncoded$MH = RuntimeHelper.downcallHandle(
        "CryptMsgCountersignEncoded",
        constants$791.CryptMsgCountersignEncoded$FUNC
    );
    static final FunctionDescriptor PFN_CMSG_ALLOC$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle PFN_CMSG_ALLOC$MH = RuntimeHelper.downcallHandle(
        constants$791.PFN_CMSG_ALLOC$FUNC
    );
}


