// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$386 {

    static final FunctionDescriptor CreateHatchBrush$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CreateHatchBrush$MH = RuntimeHelper.downcallHandle(
        "CreateHatchBrush",
        constants$386.CreateHatchBrush$FUNC
    );
    static final FunctionDescriptor CreateICA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateICA$MH = RuntimeHelper.downcallHandle(
        "CreateICA",
        constants$386.CreateICA$FUNC
    );
    static final FunctionDescriptor CreateICW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateICW$MH = RuntimeHelper.downcallHandle(
        "CreateICW",
        constants$386.CreateICW$FUNC
    );
    static final FunctionDescriptor CreateMetaFileA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateMetaFileA$MH = RuntimeHelper.downcallHandle(
        "CreateMetaFileA",
        constants$386.CreateMetaFileA$FUNC
    );
    static final FunctionDescriptor CreateMetaFileW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateMetaFileW$MH = RuntimeHelper.downcallHandle(
        "CreateMetaFileW",
        constants$386.CreateMetaFileW$FUNC
    );
    static final FunctionDescriptor CreatePalette$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreatePalette$MH = RuntimeHelper.downcallHandle(
        "CreatePalette",
        constants$386.CreatePalette$FUNC
    );
}


