// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$394 {

    static final FunctionDescriptor GetDCPenColor$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDCPenColor$MH = RuntimeHelper.downcallHandle(
        "GetDCPenColor",
        constants$394.GetDCPenColor$FUNC
    );
    static final FunctionDescriptor GetBkMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBkMode$MH = RuntimeHelper.downcallHandle(
        "GetBkMode",
        constants$394.GetBkMode$FUNC
    );
    static final FunctionDescriptor GetBitmapBits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBitmapBits$MH = RuntimeHelper.downcallHandle(
        "GetBitmapBits",
        constants$394.GetBitmapBits$FUNC
    );
    static final FunctionDescriptor GetBitmapDimensionEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBitmapDimensionEx$MH = RuntimeHelper.downcallHandle(
        "GetBitmapDimensionEx",
        constants$394.GetBitmapDimensionEx$FUNC
    );
    static final FunctionDescriptor GetBoundsRect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetBoundsRect$MH = RuntimeHelper.downcallHandle(
        "GetBoundsRect",
        constants$394.GetBoundsRect$FUNC
    );
    static final FunctionDescriptor GetBrushOrgEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetBrushOrgEx$MH = RuntimeHelper.downcallHandle(
        "GetBrushOrgEx",
        constants$394.GetBrushOrgEx$FUNC
    );
}


