// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1282 {

    static final FunctionDescriptor ImmUnregisterWordW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmUnregisterWordW$MH = RuntimeHelper.downcallHandle(
        "ImmUnregisterWordW",
        constants$1282.ImmUnregisterWordW$FUNC
    );
    static final FunctionDescriptor ImmGetRegisterWordStyleA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetRegisterWordStyleA$MH = RuntimeHelper.downcallHandle(
        "ImmGetRegisterWordStyleA",
        constants$1282.ImmGetRegisterWordStyleA$FUNC
    );
    static final FunctionDescriptor ImmGetRegisterWordStyleW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmGetRegisterWordStyleW$MH = RuntimeHelper.downcallHandle(
        "ImmGetRegisterWordStyleW",
        constants$1282.ImmGetRegisterWordStyleW$FUNC
    );
    static final FunctionDescriptor ImmEnumRegisterWordA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmEnumRegisterWordA$MH = RuntimeHelper.downcallHandle(
        "ImmEnumRegisterWordA",
        constants$1282.ImmEnumRegisterWordA$FUNC
    );
    static final FunctionDescriptor ImmEnumRegisterWordW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ImmEnumRegisterWordW$MH = RuntimeHelper.downcallHandle(
        "ImmEnumRegisterWordW",
        constants$1282.ImmEnumRegisterWordW$FUNC
    );
    static final FunctionDescriptor ImmDisableIME$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ImmDisableIME$MH = RuntimeHelper.downcallHandle(
        "ImmDisableIME",
        constants$1282.ImmDisableIME$FUNC
    );
}


