// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$636 {

    static final FunctionDescriptor WNetAddConnection2W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetAddConnection2W$MH = RuntimeHelper.downcallHandle(
        "WNetAddConnection2W",
        constants$636.WNetAddConnection2W$FUNC
    );
    static final FunctionDescriptor WNetAddConnection3A$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetAddConnection3A$MH = RuntimeHelper.downcallHandle(
        "WNetAddConnection3A",
        constants$636.WNetAddConnection3A$FUNC
    );
    static final FunctionDescriptor WNetAddConnection3W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetAddConnection3W$MH = RuntimeHelper.downcallHandle(
        "WNetAddConnection3W",
        constants$636.WNetAddConnection3W$FUNC
    );
    static final FunctionDescriptor WNetAddConnection4A$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetAddConnection4A$MH = RuntimeHelper.downcallHandle(
        "WNetAddConnection4A",
        constants$636.WNetAddConnection4A$FUNC
    );
    static final FunctionDescriptor WNetAddConnection4W$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetAddConnection4W$MH = RuntimeHelper.downcallHandle(
        "WNetAddConnection4W",
        constants$636.WNetAddConnection4W$FUNC
    );
    static final FunctionDescriptor WNetCancelConnectionA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle WNetCancelConnectionA$MH = RuntimeHelper.downcallHandle(
        "WNetCancelConnectionA",
        constants$636.WNetCancelConnectionA$FUNC
    );
}


