// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1040 {

    static final FunctionDescriptor HICON_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HICON_UserFree64$MH = RuntimeHelper.downcallHandle(
        "HICON_UserFree64",
        constants$1040.HICON_UserFree64$FUNC
    );
    static final FunctionDescriptor SNB_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SNB_UserSize64$MH = RuntimeHelper.downcallHandle(
        "SNB_UserSize64",
        constants$1040.SNB_UserSize64$FUNC
    );
    static final FunctionDescriptor SNB_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SNB_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "SNB_UserMarshal64",
        constants$1040.SNB_UserMarshal64$FUNC
    );
    static final FunctionDescriptor SNB_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SNB_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "SNB_UserUnmarshal64",
        constants$1040.SNB_UserUnmarshal64$FUNC
    );
    static final FunctionDescriptor SNB_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SNB_UserFree64$MH = RuntimeHelper.downcallHandle(
        "SNB_UserFree64",
        constants$1040.SNB_UserFree64$FUNC
    );
    static final FunctionDescriptor STGMEDIUM_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle STGMEDIUM_UserSize64$MH = RuntimeHelper.downcallHandle(
        "STGMEDIUM_UserSize64",
        constants$1040.STGMEDIUM_UserSize64$FUNC
    );
}


