// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$586 {

    static final FunctionDescriptor GetNumberFormatW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetNumberFormatW$MH = RuntimeHelper.downcallHandle(
        "GetNumberFormatW",
        constants$586.GetNumberFormatW$FUNC
    );
    static final FunctionDescriptor GetCurrencyFormatA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCurrencyFormatA$MH = RuntimeHelper.downcallHandle(
        "GetCurrencyFormatA",
        constants$586.GetCurrencyFormatA$FUNC
    );
    static final FunctionDescriptor GetCurrencyFormatW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCurrencyFormatW$MH = RuntimeHelper.downcallHandle(
        "GetCurrencyFormatW",
        constants$586.GetCurrencyFormatW$FUNC
    );
    static final FunctionDescriptor EnumCalendarInfoA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumCalendarInfoA$MH = RuntimeHelper.downcallHandle(
        "EnumCalendarInfoA",
        constants$586.EnumCalendarInfoA$FUNC
    );
    static final FunctionDescriptor EnumCalendarInfoW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumCalendarInfoW$MH = RuntimeHelper.downcallHandle(
        "EnumCalendarInfoW",
        constants$586.EnumCalendarInfoW$FUNC
    );
    static final FunctionDescriptor EnumCalendarInfoExA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle EnumCalendarInfoExA$MH = RuntimeHelper.downcallHandle(
        "EnumCalendarInfoExA",
        constants$586.EnumCalendarInfoExA$FUNC
    );
}


