// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$653 {

    static final FunctionDescriptor YIELDPROC$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle YIELDPROC$MH = RuntimeHelper.downcallHandle(
        constants$653.YIELDPROC$FUNC
    );
    static final FunctionDescriptor mciSendCommandA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mciSendCommandA$MH = RuntimeHelper.downcallHandle(
        "mciSendCommandA",
        constants$653.mciSendCommandA$FUNC
    );
    static final FunctionDescriptor mciSendCommandW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle mciSendCommandW$MH = RuntimeHelper.downcallHandle(
        "mciSendCommandW",
        constants$653.mciSendCommandW$FUNC
    );
    static final FunctionDescriptor mciSendStringA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mciSendStringA$MH = RuntimeHelper.downcallHandle(
        "mciSendStringA",
        constants$653.mciSendStringA$FUNC
    );
    static final FunctionDescriptor mciSendStringW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mciSendStringW$MH = RuntimeHelper.downcallHandle(
        "mciSendStringW",
        constants$653.mciSendStringW$FUNC
    );
}


