// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$686 {

    static final FunctionDescriptor RPC_IF_CALLBACK_FN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_IF_CALLBACK_FN$MH = RuntimeHelper.downcallHandle(
        constants$686.RPC_IF_CALLBACK_FN$FUNC
    );
    static final FunctionDescriptor RPC_SECURITY_CALLBACK_FN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RPC_SECURITY_CALLBACK_FN$MH = RuntimeHelper.downcallHandle(
        constants$686.RPC_SECURITY_CALLBACK_FN$FUNC
    );
    static final FunctionDescriptor RpcBindingCopy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingCopy$MH = RuntimeHelper.downcallHandle(
        "RpcBindingCopy",
        constants$686.RpcBindingCopy$FUNC
    );
    static final FunctionDescriptor RpcBindingFree$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcBindingFree$MH = RuntimeHelper.downcallHandle(
        "RpcBindingFree",
        constants$686.RpcBindingFree$FUNC
    );
    static final FunctionDescriptor RpcBindingSetOption$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle RpcBindingSetOption$MH = RuntimeHelper.downcallHandle(
        "RpcBindingSetOption",
        constants$686.RpcBindingSetOption$FUNC
    );
}


