// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$771 {

    static final FunctionDescriptor BCryptImportKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle BCryptImportKey$MH = RuntimeHelper.downcallHandle(
        "BCryptImportKey",
        constants$771.BCryptImportKey$FUNC
    );
    static final FunctionDescriptor BCryptImportKeyPair$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle BCryptImportKeyPair$MH = RuntimeHelper.downcallHandle(
        "BCryptImportKeyPair",
        constants$771.BCryptImportKeyPair$FUNC
    );
    static final FunctionDescriptor BCryptDuplicateKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle BCryptDuplicateKey$MH = RuntimeHelper.downcallHandle(
        "BCryptDuplicateKey",
        constants$771.BCryptDuplicateKey$FUNC
    );
    static final FunctionDescriptor BCryptFinalizeKeyPair$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle BCryptFinalizeKeyPair$MH = RuntimeHelper.downcallHandle(
        "BCryptFinalizeKeyPair",
        constants$771.BCryptFinalizeKeyPair$FUNC
    );
    static final FunctionDescriptor BCryptDestroyKey$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptDestroyKey$MH = RuntimeHelper.downcallHandle(
        "BCryptDestroyKey",
        constants$771.BCryptDestroyKey$FUNC
    );
    static final FunctionDescriptor BCryptDestroySecret$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BCryptDestroySecret$MH = RuntimeHelper.downcallHandle(
        "BCryptDestroySecret",
        constants$771.BCryptDestroySecret$FUNC
    );
}


