// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$316 {

    static final FunctionDescriptor CloseEncryptedFileRaw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CloseEncryptedFileRaw$MH = RuntimeHelper.downcallHandle(
        "CloseEncryptedFileRaw",
        constants$316.CloseEncryptedFileRaw$FUNC
    );
    static final FunctionDescriptor lstrcmpA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpA$MH = RuntimeHelper.downcallHandle(
        "lstrcmpA",
        constants$316.lstrcmpA$FUNC
    );
    static final FunctionDescriptor lstrcmpW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpW$MH = RuntimeHelper.downcallHandle(
        "lstrcmpW",
        constants$316.lstrcmpW$FUNC
    );
    static final FunctionDescriptor lstrcmpiA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpiA$MH = RuntimeHelper.downcallHandle(
        "lstrcmpiA",
        constants$316.lstrcmpiA$FUNC
    );
    static final FunctionDescriptor lstrcmpiW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstrcmpiW$MH = RuntimeHelper.downcallHandle(
        "lstrcmpiW",
        constants$316.lstrcmpiW$FUNC
    );
    static final FunctionDescriptor lstrcpynA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle lstrcpynA$MH = RuntimeHelper.downcallHandle(
        "lstrcpynA",
        constants$316.lstrcpynA$FUNC
    );
}


