// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$751 {

    static final FunctionDescriptor ExtractAssociatedIconA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractAssociatedIconA$MH = RuntimeHelper.downcallHandle(
        "ExtractAssociatedIconA",
        constants$751.ExtractAssociatedIconA$FUNC
    );
    static final FunctionDescriptor ExtractAssociatedIconW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractAssociatedIconW$MH = RuntimeHelper.downcallHandle(
        "ExtractAssociatedIconW",
        constants$751.ExtractAssociatedIconW$FUNC
    );
    static final FunctionDescriptor ExtractAssociatedIconExA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractAssociatedIconExA$MH = RuntimeHelper.downcallHandle(
        "ExtractAssociatedIconExA",
        constants$751.ExtractAssociatedIconExA$FUNC
    );
    static final FunctionDescriptor ExtractAssociatedIconExW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ExtractAssociatedIconExW$MH = RuntimeHelper.downcallHandle(
        "ExtractAssociatedIconExW",
        constants$751.ExtractAssociatedIconExW$FUNC
    );
    static final FunctionDescriptor ExtractIconA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ExtractIconA$MH = RuntimeHelper.downcallHandle(
        "ExtractIconA",
        constants$751.ExtractIconA$FUNC
    );
    static final FunctionDescriptor ExtractIconW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ExtractIconW$MH = RuntimeHelper.downcallHandle(
        "ExtractIconW",
        constants$751.ExtractIconW$FUNC
    );
}


