// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1467 {

    static final MemoryAddress PKCS_SMIME_CAPABILITIES$ADDR = MemoryAddress.ofLong(42L);
    static final MemoryAddress X509_QC_STATEMENTS_EXT$ADDR = MemoryAddress.ofLong(42L);
    static final MemoryAddress PKCS_RSA_PRIVATE_KEY$ADDR = MemoryAddress.ofLong(43L);
    static final MemoryAddress PKCS_PRIVATE_KEY_INFO$ADDR = MemoryAddress.ofLong(44L);
    static final MemoryAddress PKCS_ENCRYPTED_PRIVATE_KEY_INFO$ADDR = MemoryAddress.ofLong(45L);
    static final MemoryAddress X509_PKIX_POLICY_QUALIFIER_USERNOTICE$ADDR = MemoryAddress.ofLong(46L);
}


