// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$877 {

    static final FunctionDescriptor NdrConformantVaryingStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConformantVaryingStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrConformantVaryingStructFree",
        constants$877.NdrConformantVaryingStructFree$FUNC
    );
    static final FunctionDescriptor NdrComplexStructFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrComplexStructFree$MH = RuntimeHelper.downcallHandle(
        "NdrComplexStructFree",
        constants$877.NdrComplexStructFree$FUNC
    );
    static final FunctionDescriptor NdrFixedArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrFixedArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrFixedArrayFree",
        constants$877.NdrFixedArrayFree$FUNC
    );
    static final FunctionDescriptor NdrConformantArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConformantArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrConformantArrayFree",
        constants$877.NdrConformantArrayFree$FUNC
    );
    static final FunctionDescriptor NdrConformantVaryingArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrConformantVaryingArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrConformantVaryingArrayFree",
        constants$877.NdrConformantVaryingArrayFree$FUNC
    );
    static final FunctionDescriptor NdrVaryingArrayFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle NdrVaryingArrayFree$MH = RuntimeHelper.downcallHandle(
        "NdrVaryingArrayFree",
        constants$877.NdrVaryingArrayFree$FUNC
    );
}


