// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$794 {

    static final FunctionDescriptor PFN_CMSG_EXPORT_KEY_AGREE$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CMSG_EXPORT_KEY_AGREE$MH = RuntimeHelper.downcallHandle(
        constants$794.PFN_CMSG_EXPORT_KEY_AGREE$FUNC
    );
    static final FunctionDescriptor PFN_CMSG_EXPORT_MAIL_LIST$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CMSG_EXPORT_MAIL_LIST$MH = RuntimeHelper.downcallHandle(
        constants$794.PFN_CMSG_EXPORT_MAIL_LIST$FUNC
    );
    static final FunctionDescriptor PFN_CMSG_IMPORT_KEY_TRANS$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PFN_CMSG_IMPORT_KEY_TRANS$MH = RuntimeHelper.downcallHandle(
        constants$794.PFN_CMSG_IMPORT_KEY_TRANS$FUNC
    );
}


