// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1588 {

    static final MemorySegment SPLDS_PRINT_ORIENTATIONS_SUPPORTED$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printOrientationsSupported");
    static final MemorySegment SPLDS_PRINT_OWNER$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printOwner");
    static final MemorySegment SPLDS_PRINT_PAGES_PER_MINUTE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printPagesPerMinute");
    static final MemorySegment SPLDS_PRINT_RATE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printRate");
    static final MemorySegment SPLDS_PRINT_RATE_UNIT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printRateUnit");
    static final MemorySegment SPLDS_PRINT_SEPARATOR_FILE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("printSeparatorFile");
}


