// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$918 {

    static final FunctionDescriptor SCardDlgExtendedError$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle SCardDlgExtendedError$MH = RuntimeHelper.downcallHandle(
        "SCardDlgExtendedError",
        constants$918.SCardDlgExtendedError$FUNC
    );
    static final FunctionDescriptor SCardReadCacheA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardReadCacheA$MH = RuntimeHelper.downcallHandle(
        "SCardReadCacheA",
        constants$918.SCardReadCacheA$FUNC
    );
    static final FunctionDescriptor SCardReadCacheW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardReadCacheW$MH = RuntimeHelper.downcallHandle(
        "SCardReadCacheW",
        constants$918.SCardReadCacheW$FUNC
    );
    static final FunctionDescriptor SCardWriteCacheA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardWriteCacheA$MH = RuntimeHelper.downcallHandle(
        "SCardWriteCacheA",
        constants$918.SCardWriteCacheA$FUNC
    );
    static final FunctionDescriptor SCardWriteCacheW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardWriteCacheW$MH = RuntimeHelper.downcallHandle(
        "SCardWriteCacheW",
        constants$918.SCardWriteCacheW$FUNC
    );
    static final FunctionDescriptor SCardGetReaderIconA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardGetReaderIconA$MH = RuntimeHelper.downcallHandle(
        "SCardGetReaderIconA",
        constants$918.SCardGetReaderIconA$FUNC
    );
}


