// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$397 {

    static final FunctionDescriptor GetMetaRgn$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetMetaRgn$MH = RuntimeHelper.downcallHandle(
        "GetMetaRgn",
        constants$397.GetMetaRgn$FUNC
    );
    static final FunctionDescriptor GetCurrentObject$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetCurrentObject$MH = RuntimeHelper.downcallHandle(
        "GetCurrentObject",
        constants$397.GetCurrentObject$FUNC
    );
    static final FunctionDescriptor GetCurrentPositionEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetCurrentPositionEx$MH = RuntimeHelper.downcallHandle(
        "GetCurrentPositionEx",
        constants$397.GetCurrentPositionEx$FUNC
    );
    static final FunctionDescriptor GetDeviceCaps$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetDeviceCaps$MH = RuntimeHelper.downcallHandle(
        "GetDeviceCaps",
        constants$397.GetDeviceCaps$FUNC
    );
    static final FunctionDescriptor GetDIBits$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetDIBits$MH = RuntimeHelper.downcallHandle(
        "GetDIBits",
        constants$397.GetDIBits$FUNC
    );
    static final FunctionDescriptor GetFontData$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle GetFontData$MH = RuntimeHelper.downcallHandle(
        "GetFontData",
        constants$397.GetFontData$FUNC
    );
}


