// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$942 {

    static final FunctionDescriptor DeletePortW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle DeletePortW$MH = RuntimeHelper.downcallHandle(
        "DeletePortW",
        constants$942.DeletePortW$FUNC
    );
    static final FunctionDescriptor XcvDataW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle XcvDataW$MH = RuntimeHelper.downcallHandle(
        "XcvDataW",
        constants$942.XcvDataW$FUNC
    );
    static final FunctionDescriptor GetDefaultPrinterA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDefaultPrinterA$MH = RuntimeHelper.downcallHandle(
        "GetDefaultPrinterA",
        constants$942.GetDefaultPrinterA$FUNC
    );
    static final FunctionDescriptor GetDefaultPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetDefaultPrinterW$MH = RuntimeHelper.downcallHandle(
        "GetDefaultPrinterW",
        constants$942.GetDefaultPrinterW$FUNC
    );
    static final FunctionDescriptor SetDefaultPrinterA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetDefaultPrinterA$MH = RuntimeHelper.downcallHandle(
        "SetDefaultPrinterA",
        constants$942.SetDefaultPrinterA$FUNC
    );
    static final FunctionDescriptor SetDefaultPrinterW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetDefaultPrinterW$MH = RuntimeHelper.downcallHandle(
        "SetDefaultPrinterW",
        constants$942.SetDefaultPrinterW$FUNC
    );
}


