// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$278 {

    static final FunctionDescriptor GetFileSecurityW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetFileSecurityW$MH = RuntimeHelper.downcallHandle(
        "GetFileSecurityW",
        constants$278.GetFileSecurityW$FUNC
    );
    static final FunctionDescriptor GetKernelObjectSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetKernelObjectSecurity$MH = RuntimeHelper.downcallHandle(
        "GetKernelObjectSecurity",
        constants$278.GetKernelObjectSecurity$FUNC
    );
    static final FunctionDescriptor GetLengthSid$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetLengthSid$MH = RuntimeHelper.downcallHandle(
        "GetLengthSid",
        constants$278.GetLengthSid$FUNC
    );
    static final FunctionDescriptor GetPrivateObjectSecurity$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetPrivateObjectSecurity$MH = RuntimeHelper.downcallHandle(
        "GetPrivateObjectSecurity",
        constants$278.GetPrivateObjectSecurity$FUNC
    );
    static final FunctionDescriptor GetSecurityDescriptorControl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetSecurityDescriptorControl$MH = RuntimeHelper.downcallHandle(
        "GetSecurityDescriptorControl",
        constants$278.GetSecurityDescriptorControl$FUNC
    );
    static final FunctionDescriptor GetSecurityDescriptorDacl$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetSecurityDescriptorDacl$MH = RuntimeHelper.downcallHandle(
        "GetSecurityDescriptorDacl",
        constants$278.GetSecurityDescriptorDacl$FUNC
    );
}


