// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$812 {

    static final FunctionDescriptor CertFindSubjectInCTL$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CertFindSubjectInCTL$MH = RuntimeHelper.downcallHandle(
        "CertFindSubjectInCTL",
        constants$812.CertFindSubjectInCTL$FUNC
    );
    static final FunctionDescriptor CertFindCTLInStore$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertFindCTLInStore$MH = RuntimeHelper.downcallHandle(
        "CertFindCTLInStore",
        constants$812.CertFindCTLInStore$FUNC
    );
    static final FunctionDescriptor CertAddEncodedCTLToStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertAddEncodedCTLToStore$MH = RuntimeHelper.downcallHandle(
        "CertAddEncodedCTLToStore",
        constants$812.CertAddEncodedCTLToStore$FUNC
    );
    static final FunctionDescriptor CertAddCTLContextToStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertAddCTLContextToStore$MH = RuntimeHelper.downcallHandle(
        "CertAddCTLContextToStore",
        constants$812.CertAddCTLContextToStore$FUNC
    );
    static final FunctionDescriptor CertSerializeCTLStoreElement$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertSerializeCTLStoreElement$MH = RuntimeHelper.downcallHandle(
        "CertSerializeCTLStoreElement",
        constants$812.CertSerializeCTLStoreElement$FUNC
    );
    static final FunctionDescriptor CertDeleteCTLFromStore$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CertDeleteCTLFromStore$MH = RuntimeHelper.downcallHandle(
        "CertDeleteCTLFromStore",
        constants$812.CertDeleteCTLFromStore$FUNC
    );
}


