// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1076 {

    static final FunctionDescriptor ITypeInfo_GetNames_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_GetNames_Proxy$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_GetNames_Proxy",
        constants$1076.ITypeInfo_GetNames_Proxy$FUNC
    );
    static final FunctionDescriptor ITypeInfo_GetNames_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_GetNames_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_GetNames_Stub",
        constants$1076.ITypeInfo_GetNames_Stub$FUNC
    );
    static final FunctionDescriptor ITypeInfo_GetIDsOfNames_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_GetIDsOfNames_Proxy$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_GetIDsOfNames_Proxy",
        constants$1076.ITypeInfo_GetIDsOfNames_Proxy$FUNC
    );
    static final FunctionDescriptor ITypeInfo_GetIDsOfNames_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_GetIDsOfNames_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_GetIDsOfNames_Stub",
        constants$1076.ITypeInfo_GetIDsOfNames_Stub$FUNC
    );
    static final FunctionDescriptor ITypeInfo_Invoke_Proxy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_Invoke_Proxy$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_Invoke_Proxy",
        constants$1076.ITypeInfo_Invoke_Proxy$FUNC
    );
    static final FunctionDescriptor ITypeInfo_Invoke_Stub$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ITypeInfo_Invoke_Stub$MH = RuntimeHelper.downcallHandle(
        "ITypeInfo_Invoke_Stub",
        constants$1076.ITypeInfo_Invoke_Stub$FUNC
    );
}


