// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1033 {

    static final FunctionDescriptor HBITMAP_UserMarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserMarshal$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserMarshal",
        constants$1033.HBITMAP_UserMarshal$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserUnmarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserUnmarshal$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserUnmarshal",
        constants$1033.HBITMAP_UserUnmarshal$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserFree$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserFree",
        constants$1033.HBITMAP_UserFree$FUNC
    );
    static final FunctionDescriptor HDC_UserSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserSize$MH = RuntimeHelper.downcallHandle(
        "HDC_UserSize",
        constants$1033.HDC_UserSize$FUNC
    );
    static final FunctionDescriptor HDC_UserMarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserMarshal$MH = RuntimeHelper.downcallHandle(
        "HDC_UserMarshal",
        constants$1033.HDC_UserMarshal$FUNC
    );
    static final FunctionDescriptor HDC_UserUnmarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserUnmarshal$MH = RuntimeHelper.downcallHandle(
        "HDC_UserUnmarshal",
        constants$1033.HDC_UserUnmarshal$FUNC
    );
}


