// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$55 {

    static final FunctionDescriptor _toupper_l$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _toupper_l$MH = RuntimeHelper.downcallHandle(
        "_toupper_l",
        constants$55._toupper_l$FUNC
    );
    static final FunctionDescriptor __isascii$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __isascii$MH = RuntimeHelper.downcallHandle(
        "__isascii",
        constants$55.__isascii$FUNC
    );
    static final FunctionDescriptor __toascii$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __toascii$MH = RuntimeHelper.downcallHandle(
        "__toascii",
        constants$55.__toascii$FUNC
    );
    static final FunctionDescriptor __iscsymf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __iscsymf$MH = RuntimeHelper.downcallHandle(
        "__iscsymf",
        constants$55.__iscsymf$FUNC
    );
    static final FunctionDescriptor __iscsym$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __iscsym$MH = RuntimeHelper.downcallHandle(
        "__iscsym",
        constants$55.__iscsym$FUNC
    );
    static final FunctionDescriptor __acrt_locale_get_ctype_array_value$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __acrt_locale_get_ctype_array_value$MH = RuntimeHelper.downcallHandle(
        "__acrt_locale_get_ctype_array_value",
        constants$55.__acrt_locale_get_ctype_array_value$FUNC
    );
}


