// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1097 {

    static final FunctionDescriptor CreateAntiMoniker$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateAntiMoniker$MH = RuntimeHelper.downcallHandle(
        "CreateAntiMoniker",
        constants$1097.CreateAntiMoniker$FUNC
    );
    static final FunctionDescriptor CreatePointerMoniker$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreatePointerMoniker$MH = RuntimeHelper.downcallHandle(
        "CreatePointerMoniker",
        constants$1097.CreatePointerMoniker$FUNC
    );
    static final FunctionDescriptor CreateObjrefMoniker$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CreateObjrefMoniker$MH = RuntimeHelper.downcallHandle(
        "CreateObjrefMoniker",
        constants$1097.CreateObjrefMoniker$FUNC
    );
    static final FunctionDescriptor GetRunningObjectTable$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetRunningObjectTable$MH = RuntimeHelper.downcallHandle(
        "GetRunningObjectTable",
        constants$1097.GetRunningObjectTable$FUNC
    );
    static final  OfAddress __MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle __MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec$VH = constants$1097.__MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec$LAYOUT.varHandle();
    static final MemorySegment __MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec$SEGMENT = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec", constants$1097.__MIDL_itf_oleidl_0000_0000_v0_0_c_ifspec$LAYOUT);
    static final  OfAddress __MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec$LAYOUT = Constants$root.C_POINTER$LAYOUT;
    static final VarHandle __MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec$VH = constants$1097.__MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec$LAYOUT.varHandle();
    static final MemorySegment __MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec$SEGMENT = RuntimeHelper.lookupGlobalVariable("__MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec", constants$1097.__MIDL_itf_oleidl_0000_0000_v0_0_s_ifspec$LAYOUT);
}


