// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$911 {

    static final FunctionDescriptor SCardIntroduceCardTypeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardIntroduceCardTypeW$MH = RuntimeHelper.downcallHandle(
        "SCardIntroduceCardTypeW",
        constants$911.SCardIntroduceCardTypeW$FUNC
    );
    static final FunctionDescriptor SCardSetCardTypeProviderNameA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardSetCardTypeProviderNameA$MH = RuntimeHelper.downcallHandle(
        "SCardSetCardTypeProviderNameA",
        constants$911.SCardSetCardTypeProviderNameA$FUNC
    );
    static final FunctionDescriptor SCardSetCardTypeProviderNameW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardSetCardTypeProviderNameW$MH = RuntimeHelper.downcallHandle(
        "SCardSetCardTypeProviderNameW",
        constants$911.SCardSetCardTypeProviderNameW$FUNC
    );
    static final FunctionDescriptor SCardForgetCardTypeA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardForgetCardTypeA$MH = RuntimeHelper.downcallHandle(
        "SCardForgetCardTypeA",
        constants$911.SCardForgetCardTypeA$FUNC
    );
    static final FunctionDescriptor SCardForgetCardTypeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardForgetCardTypeW$MH = RuntimeHelper.downcallHandle(
        "SCardForgetCardTypeW",
        constants$911.SCardForgetCardTypeW$FUNC
    );
    static final FunctionDescriptor SCardFreeMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardFreeMemory$MH = RuntimeHelper.downcallHandle(
        "SCardFreeMemory",
        constants$911.SCardFreeMemory$FUNC
    );
}


