// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$247 {

    static final FunctionDescriptor OpenFileMappingFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle OpenFileMappingFromApp$MH = RuntimeHelper.downcallHandle(
        "OpenFileMappingFromApp",
        constants$247.OpenFileMappingFromApp$FUNC
    );
    static final FunctionDescriptor QueryVirtualMemoryInformation$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle QueryVirtualMemoryInformation$MH = RuntimeHelper.downcallHandle(
        "QueryVirtualMemoryInformation",
        constants$247.QueryVirtualMemoryInformation$FUNC
    );
    static final FunctionDescriptor MapViewOfFileNuma2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle MapViewOfFileNuma2$MH = RuntimeHelper.downcallHandle(
        "MapViewOfFileNuma2",
        constants$247.MapViewOfFileNuma2$FUNC
    );
    static final FunctionDescriptor MapViewOfFile2$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle MapViewOfFile2$MH = RuntimeHelper.downcallHandle(
        "MapViewOfFile2",
        constants$247.MapViewOfFile2$FUNC
    );
    static final FunctionDescriptor UnmapViewOfFile2$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle UnmapViewOfFile2$MH = RuntimeHelper.downcallHandle(
        "UnmapViewOfFile2",
        constants$247.UnmapViewOfFile2$FUNC
    );
    static final FunctionDescriptor VirtualUnlockEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle VirtualUnlockEx$MH = RuntimeHelper.downcallHandle(
        "VirtualUnlockEx",
        constants$247.VirtualUnlockEx$FUNC
    );
}


