// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$989 {

    static final FunctionDescriptor CoGetObjectContext$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetObjectContext$MH = RuntimeHelper.downcallHandle(
        "CoGetObjectContext",
        constants$989.CoGetObjectContext$FUNC
    );
    static final FunctionDescriptor CoGetClassObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetClassObject$MH = RuntimeHelper.downcallHandle(
        "CoGetClassObject",
        constants$989.CoGetClassObject$FUNC
    );
    static final FunctionDescriptor CoRegisterClassObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoRegisterClassObject$MH = RuntimeHelper.downcallHandle(
        "CoRegisterClassObject",
        constants$989.CoRegisterClassObject$FUNC
    );
    static final FunctionDescriptor CoRevokeClassObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle CoRevokeClassObject$MH = RuntimeHelper.downcallHandle(
        "CoRevokeClassObject",
        constants$989.CoRevokeClassObject$FUNC
    );
    static final FunctionDescriptor CoResumeClassObjects$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoResumeClassObjects$MH = RuntimeHelper.downcallHandle(
        "CoResumeClassObjects",
        constants$989.CoResumeClassObjects$FUNC
    );
    static final FunctionDescriptor CoSuspendClassObjects$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle CoSuspendClassObjects$MH = RuntimeHelper.downcallHandle(
        "CoSuspendClassObjects",
        constants$989.CoSuspendClassObjects$FUNC
    );
}


