// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1072 {

    static final FunctionDescriptor BSTR_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BSTR_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "BSTR_UserUnmarshal64",
        constants$1072.BSTR_UserUnmarshal64$FUNC
    );
    static final FunctionDescriptor BSTR_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BSTR_UserFree64$MH = RuntimeHelper.downcallHandle(
        "BSTR_UserFree64",
        constants$1072.BSTR_UserFree64$FUNC
    );
    static final FunctionDescriptor CLEANLOCALSTORAGE_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLEANLOCALSTORAGE_UserSize64$MH = RuntimeHelper.downcallHandle(
        "CLEANLOCALSTORAGE_UserSize64",
        constants$1072.CLEANLOCALSTORAGE_UserSize64$FUNC
    );
    static final FunctionDescriptor CLEANLOCALSTORAGE_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLEANLOCALSTORAGE_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "CLEANLOCALSTORAGE_UserMarshal64",
        constants$1072.CLEANLOCALSTORAGE_UserMarshal64$FUNC
    );
    static final FunctionDescriptor CLEANLOCALSTORAGE_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLEANLOCALSTORAGE_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "CLEANLOCALSTORAGE_UserUnmarshal64",
        constants$1072.CLEANLOCALSTORAGE_UserUnmarshal64$FUNC
    );
    static final FunctionDescriptor CLEANLOCALSTORAGE_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLEANLOCALSTORAGE_UserFree64$MH = RuntimeHelper.downcallHandle(
        "CLEANLOCALSTORAGE_UserFree64",
        constants$1072.CLEANLOCALSTORAGE_UserFree64$FUNC
    );
}


