// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1039 {

    static final FunctionDescriptor HDC_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "HDC_UserMarshal64",
        constants$1039.HDC_UserMarshal64$FUNC
    );
    static final FunctionDescriptor HDC_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "HDC_UserUnmarshal64",
        constants$1039.HDC_UserUnmarshal64$FUNC
    );
    static final FunctionDescriptor HDC_UserFree64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HDC_UserFree64$MH = RuntimeHelper.downcallHandle(
        "HDC_UserFree64",
        constants$1039.HDC_UserFree64$FUNC
    );
    static final FunctionDescriptor HICON_UserSize64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HICON_UserSize64$MH = RuntimeHelper.downcallHandle(
        "HICON_UserSize64",
        constants$1039.HICON_UserSize64$FUNC
    );
    static final FunctionDescriptor HICON_UserMarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HICON_UserMarshal64$MH = RuntimeHelper.downcallHandle(
        "HICON_UserMarshal64",
        constants$1039.HICON_UserMarshal64$FUNC
    );
    static final FunctionDescriptor HICON_UserUnmarshal64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HICON_UserUnmarshal64$MH = RuntimeHelper.downcallHandle(
        "HICON_UserUnmarshal64",
        constants$1039.HICON_UserUnmarshal64$FUNC
    );
}


