// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$159 {

    static final FunctionDescriptor WORKERCALLBACKFUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WORKERCALLBACKFUNC$MH = RuntimeHelper.downcallHandle(
        constants$159.WORKERCALLBACKFUNC$FUNC
    );
    static final FunctionDescriptor APC_CALLBACK_FUNCTION$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle APC_CALLBACK_FUNCTION$MH = RuntimeHelper.downcallHandle(
        constants$159.APC_CALLBACK_FUNCTION$FUNC
    );
    static final FunctionDescriptor WAITORTIMERCALLBACK$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle WAITORTIMERCALLBACK$MH = RuntimeHelper.downcallHandle(
        constants$159.WAITORTIMERCALLBACK$FUNC
    );
}


