// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$23 {

    static final FunctionDescriptor labs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle labs$MH = RuntimeHelper.downcallHandle(
        "labs",
        constants$23.labs$FUNC
    );
    static final FunctionDescriptor llabs$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle llabs$MH = RuntimeHelper.downcallHandle(
        "llabs",
        constants$23.llabs$FUNC
    );
    static final FunctionDescriptor _abs64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _abs64$MH = RuntimeHelper.downcallHandle(
        "_abs64",
        constants$23._abs64$FUNC
    );
    static final FunctionDescriptor _byteswap_ushort$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle _byteswap_ushort$MH = RuntimeHelper.downcallHandle(
        "_byteswap_ushort",
        constants$23._byteswap_ushort$FUNC
    );
    static final FunctionDescriptor _byteswap_ulong$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _byteswap_ulong$MH = RuntimeHelper.downcallHandle(
        "_byteswap_ulong",
        constants$23._byteswap_ulong$FUNC
    );
    static final FunctionDescriptor _byteswap_uint64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _byteswap_uint64$MH = RuntimeHelper.downcallHandle(
        "_byteswap_uint64",
        constants$23._byteswap_uint64$FUNC
    );
}


