// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$689 {

    static final FunctionDescriptor RpcStringBindingComposeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcStringBindingComposeW$MH = RuntimeHelper.downcallHandle(
        "RpcStringBindingComposeW",
        constants$689.RpcStringBindingComposeW$FUNC
    );
    static final FunctionDescriptor RpcStringBindingParseA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcStringBindingParseA$MH = RuntimeHelper.downcallHandle(
        "RpcStringBindingParseA",
        constants$689.RpcStringBindingParseA$FUNC
    );
    static final FunctionDescriptor RpcStringBindingParseW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcStringBindingParseW$MH = RuntimeHelper.downcallHandle(
        "RpcStringBindingParseW",
        constants$689.RpcStringBindingParseW$FUNC
    );
    static final FunctionDescriptor RpcStringFreeA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcStringFreeA$MH = RuntimeHelper.downcallHandle(
        "RpcStringFreeA",
        constants$689.RpcStringFreeA$FUNC
    );
    static final FunctionDescriptor RpcStringFreeW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcStringFreeW$MH = RuntimeHelper.downcallHandle(
        "RpcStringFreeW",
        constants$689.RpcStringFreeW$FUNC
    );
    static final FunctionDescriptor RpcIfInqId$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle RpcIfInqId$MH = RuntimeHelper.downcallHandle(
        "RpcIfInqId",
        constants$689.RpcIfInqId$FUNC
    );
}


