// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1095 {

    static final FunctionDescriptor CoInstall$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoInstall$MH = RuntimeHelper.downcallHandle(
        "CoInstall",
        constants$1095.CoInstall$FUNC
    );
    static final FunctionDescriptor BindMoniker$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle BindMoniker$MH = RuntimeHelper.downcallHandle(
        "BindMoniker",
        constants$1095.BindMoniker$FUNC
    );
    static final FunctionDescriptor CoGetObject$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CoGetObject$MH = RuntimeHelper.downcallHandle(
        "CoGetObject",
        constants$1095.CoGetObject$FUNC
    );
    static final FunctionDescriptor MkParseDisplayName$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MkParseDisplayName$MH = RuntimeHelper.downcallHandle(
        "MkParseDisplayName",
        constants$1095.MkParseDisplayName$FUNC
    );
    static final FunctionDescriptor MonikerRelativePathTo$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle MonikerRelativePathTo$MH = RuntimeHelper.downcallHandle(
        "MonikerRelativePathTo",
        constants$1095.MonikerRelativePathTo$FUNC
    );
    static final FunctionDescriptor MonikerCommonPrefixWith$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle MonikerCommonPrefixWith$MH = RuntimeHelper.downcallHandle(
        "MonikerCommonPrefixWith",
        constants$1095.MonikerCommonPrefixWith$FUNC
    );
}


