// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$914 {

    static final FunctionDescriptor SCardDisconnect$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardDisconnect$MH = RuntimeHelper.downcallHandle(
        "SCardDisconnect",
        constants$914.SCardDisconnect$FUNC
    );
    static final FunctionDescriptor SCardBeginTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SCardBeginTransaction$MH = RuntimeHelper.downcallHandle(
        "SCardBeginTransaction",
        constants$914.SCardBeginTransaction$FUNC
    );
    static final FunctionDescriptor SCardEndTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SCardEndTransaction$MH = RuntimeHelper.downcallHandle(
        "SCardEndTransaction",
        constants$914.SCardEndTransaction$FUNC
    );
    static final FunctionDescriptor SCardCancelTransaction$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SCardCancelTransaction$MH = RuntimeHelper.downcallHandle(
        "SCardCancelTransaction",
        constants$914.SCardCancelTransaction$FUNC
    );
    static final FunctionDescriptor SCardState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardState$MH = RuntimeHelper.downcallHandle(
        "SCardState",
        constants$914.SCardState$FUNC
    );
    static final FunctionDescriptor SCardStatusA$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SCardStatusA$MH = RuntimeHelper.downcallHandle(
        "SCardStatusA",
        constants$914.SCardStatusA$FUNC
    );
}


