// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$453 {

    static final FunctionDescriptor wsprintfW$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wsprintfW$MH = RuntimeHelper.downcallHandleVariadic(
        "wsprintfW",
        constants$453.wsprintfW$FUNC
    );
    static final FunctionDescriptor LoadKeyboardLayoutA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle LoadKeyboardLayoutA$MH = RuntimeHelper.downcallHandle(
        "LoadKeyboardLayoutA",
        constants$453.LoadKeyboardLayoutA$FUNC
    );
    static final FunctionDescriptor LoadKeyboardLayoutW$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle LoadKeyboardLayoutW$MH = RuntimeHelper.downcallHandle(
        "LoadKeyboardLayoutW",
        constants$453.LoadKeyboardLayoutW$FUNC
    );
    static final FunctionDescriptor ActivateKeyboardLayout$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle ActivateKeyboardLayout$MH = RuntimeHelper.downcallHandle(
        "ActivateKeyboardLayout",
        constants$453.ActivateKeyboardLayout$FUNC
    );
    static final FunctionDescriptor ToUnicodeEx$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ToUnicodeEx$MH = RuntimeHelper.downcallHandle(
        "ToUnicodeEx",
        constants$453.ToUnicodeEx$FUNC
    );
    static final FunctionDescriptor UnloadKeyboardLayout$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle UnloadKeyboardLayout$MH = RuntimeHelper.downcallHandle(
        "UnloadKeyboardLayout",
        constants$453.UnloadKeyboardLayout$FUNC
    );
}


