// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$246 {

    static final FunctionDescriptor ReclaimVirtualMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle ReclaimVirtualMemory$MH = RuntimeHelper.downcallHandle(
        "ReclaimVirtualMemory",
        constants$246.ReclaimVirtualMemory$FUNC
    );
    static final FunctionDescriptor DiscardVirtualMemory$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle DiscardVirtualMemory$MH = RuntimeHelper.downcallHandle(
        "DiscardVirtualMemory",
        constants$246.DiscardVirtualMemory$FUNC
    );
    static final FunctionDescriptor SetProcessValidCallTargets$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetProcessValidCallTargets$MH = RuntimeHelper.downcallHandle(
        "SetProcessValidCallTargets",
        constants$246.SetProcessValidCallTargets$FUNC
    );
    static final FunctionDescriptor SetProcessValidCallTargetsForMappedView$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle SetProcessValidCallTargetsForMappedView$MH = RuntimeHelper.downcallHandle(
        "SetProcessValidCallTargetsForMappedView",
        constants$246.SetProcessValidCallTargetsForMappedView$FUNC
    );
    static final FunctionDescriptor VirtualAllocFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle VirtualAllocFromApp$MH = RuntimeHelper.downcallHandle(
        "VirtualAllocFromApp",
        constants$246.VirtualAllocFromApp$FUNC
    );
    static final FunctionDescriptor VirtualProtectFromApp$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle VirtualProtectFromApp$MH = RuntimeHelper.downcallHandle(
        "VirtualProtectFromApp",
        constants$246.VirtualProtectFromApp$FUNC
    );
}


