// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$415 {

    static final FunctionDescriptor GetLayout$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GetLayout$MH = RuntimeHelper.downcallHandle(
        "GetLayout",
        constants$415.GetLayout$FUNC
    );
    static final FunctionDescriptor SetMetaFileBitsEx$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetMetaFileBitsEx$MH = RuntimeHelper.downcallHandle(
        "SetMetaFileBitsEx",
        constants$415.SetMetaFileBitsEx$FUNC
    );
    static final FunctionDescriptor SetPaletteEntries$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetPaletteEntries$MH = RuntimeHelper.downcallHandle(
        "SetPaletteEntries",
        constants$415.SetPaletteEntries$FUNC
    );
    static final FunctionDescriptor SetPixel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetPixel$MH = RuntimeHelper.downcallHandle(
        "SetPixel",
        constants$415.SetPixel$FUNC
    );
    static final FunctionDescriptor SetPixelV$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle SetPixelV$MH = RuntimeHelper.downcallHandle(
        "SetPixelV",
        constants$415.SetPixelV$FUNC
    );
    static final FunctionDescriptor SetPixelFormat$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle SetPixelFormat$MH = RuntimeHelper.downcallHandle(
        "SetPixelFormat",
        constants$415.SetPixelFormat$FUNC
    );
}


