// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1032 {

    static final FunctionDescriptor CLIPFORMAT_UserFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle CLIPFORMAT_UserFree$MH = RuntimeHelper.downcallHandle(
        "CLIPFORMAT_UserFree",
        constants$1032.CLIPFORMAT_UserFree$FUNC
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FLAG_STGMEDIUM_UserSize$MH = RuntimeHelper.downcallHandle(
        "FLAG_STGMEDIUM_UserSize",
        constants$1032.FLAG_STGMEDIUM_UserSize$FUNC
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserMarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FLAG_STGMEDIUM_UserMarshal$MH = RuntimeHelper.downcallHandle(
        "FLAG_STGMEDIUM_UserMarshal",
        constants$1032.FLAG_STGMEDIUM_UserMarshal$FUNC
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserUnmarshal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FLAG_STGMEDIUM_UserUnmarshal$MH = RuntimeHelper.downcallHandle(
        "FLAG_STGMEDIUM_UserUnmarshal",
        constants$1032.FLAG_STGMEDIUM_UserUnmarshal$FUNC
    );
    static final FunctionDescriptor FLAG_STGMEDIUM_UserFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle FLAG_STGMEDIUM_UserFree$MH = RuntimeHelper.downcallHandle(
        "FLAG_STGMEDIUM_UserFree",
        constants$1032.FLAG_STGMEDIUM_UserFree$FUNC
    );
    static final FunctionDescriptor HBITMAP_UserSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle HBITMAP_UserSize$MH = RuntimeHelper.downcallHandle(
        "HBITMAP_UserSize",
        constants$1032.HBITMAP_UserSize$FUNC
    );
}


