// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1119 {

    static final  GroupLayout IID_IXMLDOMNotation$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IXMLDOMNotation$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IXMLDOMNotation", constants$1119.IID_IXMLDOMNotation$LAYOUT);
    static final  GroupLayout IID_IXMLDOMEntity$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IXMLDOMEntity$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IXMLDOMEntity", constants$1119.IID_IXMLDOMEntity$LAYOUT);
    static final  GroupLayout IID_IXMLDOMEntityReference$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IXMLDOMEntityReference$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IXMLDOMEntityReference", constants$1119.IID_IXMLDOMEntityReference$LAYOUT);
    static final  GroupLayout IID_IXMLDOMParseError$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IXMLDOMParseError$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IXMLDOMParseError", constants$1119.IID_IXMLDOMParseError$LAYOUT);
    static final  GroupLayout IID_IXTLRuntime$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment IID_IXTLRuntime$SEGMENT = RuntimeHelper.lookupGlobalVariable("IID_IXTLRuntime", constants$1119.IID_IXTLRuntime$LAYOUT);
    static final  GroupLayout DIID_XMLDOMDocumentEvents$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("Data1"),
        Constants$root.C_SHORT$LAYOUT.withName("Data2"),
        Constants$root.C_SHORT$LAYOUT.withName("Data3"),
        MemoryLayout.sequenceLayout(8, Constants$root.C_CHAR$LAYOUT).withName("Data4")
    ).withName("_GUID");
    static final MemorySegment DIID_XMLDOMDocumentEvents$SEGMENT = RuntimeHelper.lookupGlobalVariable("DIID_XMLDOMDocumentEvents", constants$1119.DIID_XMLDOMDocumentEvents$LAYOUT);
}


