// Generated by jextract

package com.jenet.enet.cpp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class SD_CHANGE_MACHINE_SID_INPUT extends _SD_CHANGE_MACHINE_SID_INPUT {

}


